### ISSUE TITLE
[BUG] Compiler bug when catching exceptions with -flto=thin

### ISSUE THREAD

**Issue by mad-rain** [android/ndk#1046]
Hi!

std::runtime_error exception is being caught inside catch(...) instead of catch(const std::exception &) when using -flto=thin, -fexceptions, -fno-rtti and c++_static as a standard library.

Minimized repro case:

[https://github.com/mad-rain/dynamic-cast-repro](https://github.com/mad-rain/dynamic-cast-repro)

Environment Details
NDK Version: 20.0.5594570
Build system: ndk-build
Host OS: Mac
Compiler: Clang
ABI: x86, armv7eabi
STL: c++_static
NDK API level: 16

Already happened for r17:

[https://github.com/android-ndk/ndk/issues/717](https://github.com/android-ndk/ndk/issues/717)

**Comment by rprichard** [comment]
@stephenhines @pirama-arumuga-nainar 

I'm not sure anymore whether LLVM's behavior here is expected or not. The problem is that we have multiple copies of a symbol, where one of them is strong, and the others are `linkonce_odr`:

 - In `libc++abi.a`: the typeinfo variables for `std::exception` and `std::runtime_error` are emitted strongly because the library is built with `-frtti`, and the key functions are present here.

 - In the app's code: the app is built with `-fno-rtti` because that's ndk-build's default option. Without LTO, the app's object files have weak+comdat versions of the standard typeinfo variables, because the compiler assumes that strong definitions won't be emitted.

I played with similar repro programs, and the problem only happened when the local copies of the typeinfo variables had `linkonce_odr` linkage in LLVM IR. When I modified the linkage to plain `linkonce` instead, the duplicate symbols in the linked output went away.

Of course, it's not generally possible to mix `-frtti` and `-fno-rtti`. If a class has a key function that's compiled with `-fno-rtti`, but all the typeinfo references are compiled with `-frtti`, then the typeinfo symbol would never be emitted. As long as the key function is compiled with `-frtti`, though, things work, except for ThinLTO maybe?

i.e. I'm wondering if the program is required to use `-frtti` or whether ThinLTO should act more like non-LTO linking. (or full LTO, which also works somehow...)

**Comment by mad-rain** [comment]
Is it going to be fixed in the upcoming release? On other platforms like iOS & Emscripten there is not such bug. We have to use NDK r19 until the bug is fixed. The main reason why we use -fno-rtti is to make executable size a little smaller.

This already happened in the past, see here:

[https://github.com/android-ndk/ndk/issues/717](url)

**Comment by DanAlbert** [comment]
Test case passes with r21.

**Comment by rprichard** [comment]
This seems to have been fixed by https://reviews.llvm.org/D61255, which fixed the LLVM bug, https://bugs.llvm.org/show_bug.cgi?id=41645. The LLVM bug looks very similar to this bug.

I'll look at adding an NDK regression test.
