### ISSUE TITLE
[BUG] llvm-ar doesn't seem to ranlib for Android targets when the host is darwin

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1082]
Submitted the change to move ndk-build and CMake over to llvm-ar (https://android-review.googlesource.com/c/platform/ndk/+/1118094) and it broke the Darwin build, seemingly because llvm-ar doesn't perform ranlib tasks by default when the host is Darwin.

I've reverted the change, but we still need to figure out what went wrong and hopefully get a fix for r21.

**Comment by pirama-arumuga-nainar** [comment]
`-format=gnu` is needed when running `llvm-ar` on Darwin, else it assumes Darwin's defaults. 
 See also https://android-review.googlesource.com/c/platform/build/soong/+/585802/

**Comment by DanAlbert** [comment]
Is that configurable? Can we make Android's do this by default? Does it harm Darwin to have the ranlib stuff happen automatically?

**Comment by pirama-arumuga-nainar** [comment]
> Is that configurable? Can we make Android's do this by default?
Not ATM - https://github.com/llvm-mirror/llvm/blob/master/tools/llvm-ar/llvm-ar.cpp#L815.  Configuring this would require plumbing a CMake variable (similar to CLANG_DEFAULT_LINKER) to llvm-ar.cpp.

 > Does it harm Darwin to have the ranlib stuff happen automatically?
The ranlib error is how this error gets surfaced.  The underlying issue is that archives are different between GNU and Darwin and by default, llvm-ar generates an archive for the host its running on.

**Comment by DanAlbert** [comment]
> The underlying issue is that archives are different between GNU and Darwin and by default, llvm-ar generates an archive for the host its running on.

Was worried it might be something like this.

Will need to think of how we want to solve this. I'm fairly unwilling to take anything that isn't command-line compatible here because that's going to cause a lot of unnecessary breakage across tons of projects, but I'm also not sure if changing the default to produce the wrong output _for_ Darwin on Darwin is a good idea either. Not sure how feasible it would be for llvm-ar to inspect the objects and make the decision based on that, but that might be a solution.

For now, moving out of r21.

**Comment by mstorsjo** [comment]
I think the "default to host format" behaviour shouldn't matter in most cases, because that is only the last fallback. If possible (operating on an existing archive, or adding object files where you can inspect the first object file, only creating the darwin format if the object file is mach-o) it will try to do the right thing: https://github.com/llvm-mirror/llvm/blob/master/tools/llvm-ar/llvm-ar.cpp#L844-L856

So while the "default to host format" behaviour is suboptimal for cross compilation, it hasn't been an issue in my use of cross compilation with llvm-ar on darwin. It'd be interesting to know exactly in which codepath it manages to miss the current sensible format detection. (That has been present since https://github.com/llvm/llvm-project/commit/a0d42c86dbcb150c2a7a3d8f2a8500dcfb98a5d1.)

**Comment by DanAlbert** [comment]
Ah, so it *does* do the autodetection like I was hoping for, we just got the error case because there's a useless empty archive being created (https://github.com/android/ndk/issues/1081).

That's good news. This should be doable for r21 after all as long as I fix the other bug too.

Thanks for the info!

**Comment by DanAlbert** [comment]
Closing this in favor of #1081, since the bug described here doesn't seem to exist.
