### ISSUE TITLE
[BUG] Unified headers: Exposing zlib.h functions with __ANDROID_API__ guards

### ISSUE THREAD

**Issue by JeromeDeBretagne** [android/ndk#1116]
#### Description

The zlib.h headers have been updated to version 1.2.7 about a year ago.

Some newer zlib functions should also be available depending on the Android API level, as described here: https://android.googlesource.com/platform/external/zlib/+/master/libz.map.txt but are not exposed currently in Android NDK zlib.h.

Would you consider in a future NDK release exposing the more recent zlib functions conditionally, with API level guards as done for libc headers?

I faced this issue actually when cross-compiling Erlang/OTP, due to a missing inflateGetDictionary declaration despite targeting API level 24:

 CC	obj/aarch64-unknown-linux-android/opt/smp/zlib_nif.o
nifs/common/zlib_nif.c:874:19: error: implicit declaration of function 'inflateGetDictionary' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if((res = inflateGetDictionary(&d->s, obin.data, &len)) < 0) {
                  ^
nifs/common/zlib_nif.c:874:19: note: did you mean 'inflateSetDictionary'?
/home/xyz/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/zlib.h:819:21: note: 'inflateSetDictionary' declared here
ZEXTERN int ZEXPORT inflateSetDictionary OF((z_streamp strm,
                    ^
1 error generated.

Thanks,
Jérôme

#### Environment Details

* NDK Version: 21.0.5935234
* Build system: Standalone toolchain
* Host OS: Linux x86_64 (Debian)
* NDK API level: 24

**Comment by enh-google** [comment]
i see that inflateGetDictionary was in 1.2.8, which we upgraded to in 2013, almost exactly one year after the 1.2.7 upgrade.

we skipped 1.2.9 in the platform, and 1.2.10 doesn't seem to have been until N. that added deflateGetDictionary/uncompress2/gzfread/gzfwrite/adler32_z/crc32_z. (but did that ship, or was that reverted and 1.2.11 was actually the first update after 1.2.8 that shipped?)

then it looks like O might have got 1.2.11 (though it's a bit unclear from the history whether that landed in O or P). 1.2.11 didn't add anything over 1.2.10 (but see my note in the previous paragraph).

(and strictly, since we never had CTS tests for any of this, we can't actually guarantee any given zlib at any given API level. OEMs could have shipped newer/older versions without us knowing.)


obviously the cleanest solution is to hop in the time machine, not include zlib in the NDK, and ship a proper package manager in all NDKs. the least-effort solution is to just wait and update this header as/when the NDK's minimum supported API level increases. at the other end of the spectrum, the dirtiest solution is to just always include the current unmodified upstream header in the NDK and let developers take their chances.

given how slowly and how little the zlib API has changed, i'm not against removing the separate NDK copy and adding `#if`s to the one true copy. (i'm assuming i'll basically never have a conflict.) but it's a bit tricky that we can't fully guarantee anything...

**Comment by enh-google** [comment]
(see also https://buganizer.corp.google.com/issues/155351357 where there's more discussion of this, with both good news [the .map.txt file already seems to have everything we need] and bad news [the `ZLIB_VERNUM` macro and friends].)

**Comment by enh-google** [comment]
work has been progressing on this. https://android-review.googlesource.com/c/platform/external/zlib/+/1299457 being the most interesting change.

this won't be in r21c, but should be in r22 i'd imagine.

**Comment by JeromeDeBretagne** [comment]
Thanks Elliott for the heads-up

**Comment by enh-google** [comment]
if you want to try this locally, you can apply the patch from https://android-review.googlesource.com/c/platform/external/zlib/+/1299457 to a local NDK.

it won't be in a nightly NDK until we manually update the sysroot. this change does that: https://android-review.googlesource.com/c/platform/prebuilts/ndk/+/1311865

**Comment by DanAlbert** [comment]
This is in canary builds now, fwiw. https://ci.android.com/builds/branches/aosp-master-ndk/grid? has the change if you want to play with it.
