### ISSUE TITLE
[DOC] ASharedMemory_create() poorly documented, no explanation on errors

### ISSUE THREAD

**Issue by atsushieno** [android/ndk#1127]
[ASharedMemory_create](https://developer.android.com/ndk/reference/group/memory#asharedmemory_create) is supposed to return an int value which is:

> file descriptor that denotes the shared memory; error code on failure. 

However there is no description on which values are errors.

I'm writing some app and getting some file descriptors like 65, 66, 67, ... And I'm quite unsure if they are valid FDs. When I use those values in another app process mmap() results in EBADF. This description  in the reference makes it hard to diagnose the issue.

**Comment by enh-google** [comment]
see here for a change that fixes the docs to expose the gory truth: https://android-review.googlesource.com/c/platform/frameworks/native/+/1164392

positive numbers should be successes. you can check /proc/self/fd to see what file descriptors you have available. i suspect your bug is "in another process" --- file descriptors are per-process, so you'll need to use ParcelFileDescriptor or whatever to access it from another process.

**Comment by enh-google** [comment]
header updated, docs will be updated after they've been through an NDK and onto the web...
