### ISSUE TITLE
[BUG] incorrect optimization produced on bitwise and expression

### ISSUE THREAD

**Issue by dkw72n** [android/ndk#1154]
#### Description

with `LOCAL_ARM_MODE := thumb` set and with optimization flag on, the clang compiler produces incorrect result on following code:

```c
#include <stdio.h>
int main(){
  int t = (int)main;
  printf("is thumb: %d\n", t & 1);
  return 0;
}
```

disassembled code shows that `t & 1` is optimized to constant 0.

```assembly
.text:000005DC                 LDR             R0, =(aIsThumbD - 0x5E4)
.text:000005DE                 MOVS            R1, #0
.text:000005E0                 ADD             R0, PC  ; "is thumb: %d\n"
.text:000005E2                 BLX             printf
```

reproduction:

https://github.com/dkw72n/wrong-optimization-repro

#### Environment Details

* NDK Version: 20.1.5948944
* Build system: ndk-build
* Host OS: Windows and Mac
* ABI: armeabi-v7a
* NDK API level: 19
* Device API level: 27

**Comment by enh-google** [comment]
looks like one for the LLVM folks... @stephenhines @pirama-arumuga-nainar

**Comment by stephenhines** [comment]
This seems to be fixed in r21 RC1.

With the latest NDK r21 RC1:
srhines@ringworld:BU:wrong-optimization-repro$ export NDK=/b/ndk/android-ndk-r21-beta2/
srhines@ringworld:BU:wrong-optimization-repro$ bash test.sh 
[armeabi-v7a] Compile thumb  : isthumb_o0 <= isthumb.c
[armeabi-v7a] Compile thumb  : isthumb_o2 <= isthumb.c
[armeabi-v7a] Executable     : isthumb_o0
[armeabi-v7a] Install        : isthumb_o0 => libs/armeabi-v7a/isthumb_o0
[armeabi-v7a] Executable     : isthumb_o2
[armeabi-v7a] Install        : isthumb_o2 => libs/armeabi-v7a/isthumb_o2
libs/armeabi-v7a/isthumb_o0: 1 file pushed. 0.3 MB/s (5708 bytes in 0.020s)
libs/armeabi-v7a/isthumb_o2: 1 file pushed. 2.4 MB/s (5708 bytes in 0.002s)
2 files pushed. 0.4 MB/s (11416 bytes in 0.026s)
is thumb: 1
is thumb: 1

With NDK R20b:
srhines@ringworld:BU:wrong-optimization-repro$ export NDK=/b/ndk/android-ndk-r20b/
srhines@ringworld:BU:wrong-optimization-repro$ bash test.sh 
[armeabi-v7a] Compile thumb  : isthumb_o0 <= isthumb.c
[armeabi-v7a] Compile thumb  : isthumb_o2 <= isthumb.c
[armeabi-v7a] Executable     : isthumb_o0
[armeabi-v7a] Executable     : isthumb_o2
[armeabi-v7a] Install        : isthumb_o0 => libs/armeabi-v7a/isthumb_o0
[armeabi-v7a] Install        : isthumb_o2 => libs/armeabi-v7a/isthumb_o2
libs/armeabi-v7a/isthumb_o0: 1 file pushed. 1.4 MB/s (5796 bytes in 0.004s)
libs/armeabi-v7a/isthumb_o2: 1 file pushed. 2.1 MB/s (5796 bytes in 0.003s)
2 files pushed. 1.2 MB/s (11592 bytes in 0.009s)
is thumb: 1
is thumb: 0

**Comment by DanAlbert** [comment]
r21 rc 1 was pushed to stable a few minutes ago, btw. Update to the latest NDK and you'll have the fix.
