### ISSUE TITLE
[question] Does libc++ support sscanf_s ??

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1164]
In https://en.cppreference.com/w/c/io/fscanf I see sscanf_s is supported since C++11, but when I try to grep libc++ header files, I found no references of it.

Does libc++ support sscanf_s? If not is there any reason why its not supporting?

Thanks.

**Comment by enh-google** [comment]
no, the annex k stuff isn't in any libc other than Microsoft's because it's a complete mess. see http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1967.htm for example.

sadly, sscanf_s is the one part that i do think had some value (because everyone gets %s counts wrong), but because the rest of annex k is so bad, i think it's been tarred with the same brush. specifically: the clang compiler doesn't support it, so although we could add it to bionic you'd probably be *worse* off because the compiler would no longer be able to sanity check your format string.

there is the %ms GNU extension, but that's only available in Android since P (https://android.googlesource.com/platform/bionic/+/master/docs/status.md), so probably not useful for you for a while.
