### ISSUE TITLE
[FR] Concepts enabled Clang 10

### ISSUE THREAD

**Issue by Zingam** [android/ndk#1174]
AFK Concepts were merged into the Clang 10 branch. Can we, please, get an updated Clang 10 version in the next Beta NDK.
https://clang.llvm.org/cxx_status.html

**Comment by DanAlbert** [comment]
I'm not sure what revision we're currently updating to but we always up date to ~latest ToT when we start am update. r22 will have a new clang.

That said, concepts are still an experimental feature so there's no guarantee of stability for them.

**Comment by Zingam** [comment]
Thank you. I remember times when the compiler updates were lagging and your current update policy is not very clear. My project is also experimental. That's why I use the latest available toolchains/NDK and I compile with with the three big compilers on three OSes of which Android TV is very important.

I'd be happy if it is possible for you to update the roadmap for 2020.

**Comment by DanAlbert** [comment]
That's a good point. I'm not sure where we could document that that it would be visible enough to be useful. For now:

Android's toolchain team is more or less constantly working on an LLVM from upstream. There's some amount of lag between each update cycle

**Comment by enh-google** [comment]
> where we could document that

i think he literally meant in the roadmap. we haven't updated it for r21 (oops), and there's a "regular maintenance" section at the top that would be a great place for what you just wrote.

the only change i'd make -- even though i understand why you were vague -- would be to give some example time frames. something like:

The NDK uses the same LLVM toolchain as the Android OS itself. Android's toolchain team is constantly working on updating to the latest upstream LLVM for the OS. It can take a long time to investigate issues when compiling -- or issues that the newer compiler finds in -- OS code or OEM code, for all 4 supported architectures, so these updates usually take several months.

Even then, a new OS toolchain may not be good enough for the NDK (which has to work for an even greater variety of code). So while we aim to have a new toolchain every quarter, we don't always have one. And because we don't want to drop in a new compiler late in an NDK release cycle for stability reasons, sometimes even when we have a new OS toolchain that is good enough for the NDK, it lands too late.

The aim is that each NDK will have a new toolchain that's as up to date as we could get without sacrificing stability, but we err on the side of stability when we have to make a choice. If an NDK release _doesn't_ include a new compiler, or that compiler isn't as new as you'd hoped, trust us --- you wouldn't want anything newer that we have just yet!

**Comment by DanAlbert** [comment]
Can do.

FYI, looks like the current update target is r377782. That could change if the team finds issues.

**Comment by DanAlbert** [comment]
Copied your blurb into the roadmap. Reworded a little bit. https://android-review.googlesource.com/c/platform/ndk/+/1229791

**Comment by Zingam** [comment]
Just as a side note: Clang 10 (libc++) doesn't implement `<concepts>` maybe this implementation can be used instead: https://github.com/cjdb/cjdb-ranges
So even if we get Clang 10 in ndk r22 it might not be useful for concepts any time soon.

**Comment by Zingam** [comment]
This should be done long time ago.
