### ISSUE TITLE
[BUG] C executable linking to C++ shared library

### ISSUE THREAD

**Issue by huangqinjin** [android/ndk#1183]
#### Environment Details

* NDK Version: any
* Build system: CMake
* Host OS: Linux
* ABI: arm64-v8a
* NDK API level: any

#### Description

`f.cpp`:
```c++
#include <iostream>
extern "C" int f()
{
    std::cout << "hello" << std::endl;
}
```

`main.c`:
```c
int f();
int main()
{
    f();
}
```

`CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.6)
project(Test)

add_library(f SHARED f.cpp)
add_executable(Test main.c)
target_link_libraries(Test f)

```

```shell
cmake .. -DCMAKE_TOOLCHAIN_FILE=${NDK}/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_STL=c++_shared && cmake --build .

warning: libc++_shared.so, needed by libf.so, not found (try using -rpath or -rpath-link)
libf.so: undefined reference to `vtable for std::length_error'
libf.so: undefined reference to `__cxa_throw'
...
```

No error for ABIs: armeabi-v7a, x86, x86_64.

**Comment by DanAlbert** [comment]
You'll need to use a different linker for arm64 if you encounter this issue. It's a bdf bug, and bfd isn't going to get updated since we're moving to LLD anyway.

Link with `-fuse-ld=lld` if you want to use lld. It's still somewhat experimental in the NDK, but we've been using it for quite a while in AOSP and as of r21 it seems to be in good shape for the NDK.

If you don't want to use lld, link with `-fuse-ld=gold`, but note that gold will produce invalid debug info for arm64.

**Comment by rprichard** [comment]
> If you don't want to use lld, link with -fuse-ld=gold, but note that gold will produce invalid debug info for arm64.

Maybe we fixed gold already?

https://android-review.googlesource.com/c/toolchain/binutils/+/716724

I think that commit appeared in r19. The r19 (and r19-beta2) tags have build 5139636 of binutils, which has commit d42268bd795ae78a45e6a225ee77c5617777223a of toolchain/binutils, which contains the above fix.

**Comment by huangqinjin** [comment]
@DanAlbert Thank you for you hint, but according to https://github.com/android/ndk/issues/829#issuecomment-432397780, arm64 defaults to the gold linker?
