### ISSUE TITLE
[question]Why the simpleperf report collected by API only contains one type of event 

### ISSUE THREAD

**Issue by forMwish** [android/ndk#1227]
Please include any context relevant to your question (NDK version, ABI, build system, etc).
NDK version : r21
Android version : 8.1

 I use simpleperf API to collect events in my app code:
```
    simpleperf::RecordOptions options;
    options.RecordDwarfCallGraph();
    options.SetEvent("cpu-cycles,instructions,cache-misses,branch-misses");
    options.TraceOffCpu();
    simpleperf::ProfileSession session;
    session.StartRecording(options);

    VectorMul();  //my function

    session.StopRecording();
``` 
but only get one event (cpu-cycles) in the report by command as follow:
```
python api_profiler.py prepare

# run the app

python api_profiler.py collect -p com.example.myfirstapp

python report_html.py .\simpleperf_data\perf-04-08-15-54-48.data --aggregate-by-thread-name

```
however, I can get all events (cpu-cycles, instructions, cache-misses, branch-misses) by using simpleperf scrips as follow:
```
python .\app_profiler.py -p com.example.myfirstapp -r "-e cpu-c
lock,instructions,cache-misses,branch-misses -f 1000 --duration 10 -g" -lib D:\work\myProject\AndroidProject\MyFirstApp\
app\libs\armeabi-v7a

python report_html.py
```

Could you help me? I will really appreciate it.

**Comment by forMwish** [comment]
I solved the problem by getting rid of  "options.TraceOffCpu()“ 😂

**Comment by yabinc** [comment]
The problem is at reporting. --trace-offcpu option will use time to the next sample (instead of event counts from the previous sample) as the weight of the current sample (as in https://android.googlesource.com/platform/system/extras/+/master/simpleperf/doc/executable_commands_reference.md#record-both-on-cpu-time-and-off-cpu-time). And it also reports all samples as belonging to the first event (as in https://android.googlesource.com/platform/system/extras/+/master/simpleperf/report_lib_interface.cpp#386).

I will add some check in record cmd when --trace-offcpu option is used, to make sure only one event is used.

**Comment by yabinc** [comment]
check added in https://android-review.googlesource.com/c/platform/system/extras/+/1282296.
