### ISSUE TITLE
[BUG] android_native_app_glue: AConfiguration_getOrientation value never changes after app startup.

### ISSUE THREAD

**Issue by Didgy74** [android/ndk#1228]
--------------------------------------------------------------------------------

#### Description

The bug is essentially that the orientation value in `AConfiguration` will never change during the lifetime of the app, even when an orientation change has occurred and the corresponding configuration-change-event has been reported.

In the `android_native_app_glue` framework, the orientation value of the `AConfiguration` object will never change from it's initial value set upon app startup. After the event `APP_CMD_CONFIG_CHANGED` has been reported, and even after grabbing the new `AConfiguration` object from the function `void AConfiguration_fromAssetManager(AConfiguration*,
  AAssetManager*)`, the value returned from `int32_t AConfiguration_getOrientation(AConfiguration*)` will be the same value as when the app start.

The easiest way to reproduce this bug is by launching the first sample "tutorial01_load_vulkan" from the Android Vulkan samples repo: https://github.com/googlesamples/android-vulkan-tutorials

When you launch the sample on your device, start reading the "Run" log. Anytime a config change occurs, the `android_native_app_glue` library will print out out a few of the values found in the new `AConfiguration object`. Rotate your device to trigger the event, the log will output something like this:
```
V/threaded_app: APP_CMD_CONFIG_CHANGED
    Config: mcc=242 mnc=1 lang=nb cnt=NO orien=1 touch=3 dens=480 keys=1 nav=1 keysHid=3 navHid=0 sdk=29 size=2 long=2 modetype=1 modenight=1
```
However, the value in `orien` will be the value it was at the initial start of the app and never change.

This makes it impossible to determine current orientation from `AConfiguration_getOrientation` and near-impossible to catch device orientation events with the `android_native_app_glue` library.

I have experienced this on more projects, but this sample seems to be the easiest way to reproduce the bug.

#### Environment Details

* NDK Version: 21.0.6113669
* Build system: CMake 3.10.2
* Host OS: Linux-Manjaro 19.02 64-bit and Window 10 1909 64-bit
* Android SDK Platform version: 29 revision 4
* Android SDK Build-Tools version: 29.0.3
* build.gradle has `compileSdkVersion` set to 29
* build.gradle has `targetSdkVerson` set to 29 
* build.gradle has `minSdkVerson` set to 26

Bug has been experienced on all 3 of my test devices:
HUAWEI Mate 20 Lite
    Android version: 10.0.0
    ABI: arm64-v8a

Samsung Galaxy A3 2017
    Android version: 8.0.0
    ABI: armeabi-v7a

Samsung Galaxy Tab A 10" 2017
    Android version: 8.1.0
    ABI: armeabi-v7a

**Comment by DanAlbert** [comment]
That sample has since been migrated to GameActivity, and doesn't appear to have that behavior any more. Recommending GameActivity is actually what I was going to do anyway. The name is a bit misleading. It's called "Game" activity because a games focused team made it, but really it's just an up-to-date `native_app_glue` (the one in the NDK hasn't been maintained for a very long time, the only reason it's still there is because we don't want to break builds that depend on it but don't need updates). https://developer.android.com/games/agdk/game-activity

I say the sample doesn't have that behavior, but it doesn't log the screen rotation state change at all. In any case, if the bug remains, it's going to be in either GameActivity or in the OS itself, neither of which are in my power to fix. If you still have the same problem with `GameActivity`, I'd start by talking to them. The "Games SDK" link on https://b.android.com is the right place for that. If you've got a strong reason to suspect it's an OS issue, use the "Framework" link instead.
