### ISSUE TITLE
[question] Understanding dynamic linker symbol resolution order

### ISSUE THREAD

**Issue by smeenai** [android/ndk#1244]
(Sorry if this isn't the right place to ask this question, and I'd appreciate a pointer to the right place if so.)

I've been trying to understand the bionic dynamic linker's symbol resolution order, as detailed in https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md. In particular, I'm interested in symbol resolution when multiple libraries define the same symbol. Here's my initial test case.

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.10.2)
project(dltest C)

add_library(a1 SHARED a1.c)

add_library(a2 SHARED a2.c)

add_library(b SHARED b.c)
target_link_libraries(b PRIVATE a2)

add_library(d SHARED d.c)
target_link_libraries(d PRIVATE a1 b)

add_executable(main main.c)
```

a1.c:
```
int a() { return 1; }
```

a2.c:
```
int a() { return 2; }
```

b.c:
```
int a(void);
int b() { return a(); }
```

d.c:
```
int b(void);
int d() { return b(); }
```

main.c:
```
#include <dlfcn.h>
#include <stdio.h>

typedef int (*d_type)(void);
int main() {
    void *libd = dlopen("libd.so", RTLD_NOW | RTLD_LOCAL);
    d_type d_ptr = (d_type)dlsym(libd, "d");
    printf("%d\n", d_ptr());
    return 0;
}
```

In other words, `liba1.so` and `liba2.so` both define a function `a`. `libb.so` has a function `b` which calls `a`, and it's linked against `liba2.so`. `libd.so` has a function `d` which calls `b`, and it's linked against both `liba1.so` and `libb.so`. (Its DT_NEEDED will be in that order as well, i.e. it'll have `liba1.so` and then `libb.so`.) My main executable dynamically loads `libd.so` and calls `d`. What I'm trying to determine here is whether symbol resolution for a library only cares about the NEEDED libraries of the library itself, or also takes the NEEDED libraries of the library which loaded that library into account.

I'm building this using the NDK r21-provided CMake toolchain. When I run the program on an API 22 emulator, it prints `2`. When I run it on an API 23 emulator, it prints `1`. I'm assuming that the relevant linker change is the following:

> Before API 23, the default search order was to try the main executable, LD_PRELOAD libraries, the library itself, and its DT_NEEDED libraries in that order. For API 23 and later, for any given library, the dynamic linker divides other libraries into the global group and the local group. The global group is shared by all libraries and contains the main executable, LD_PRELOAD libraries, and any library with the DF_1_GLOBAL flag set (by passing “-z global” to ld(1)). The local group is the breadth-first transitive closure of the library and its DT_NEEDED libraries. The M dynamic linker searches the global group followed by the local group. This allows ASAN, for example, to ensure that it can intercept any symbol.

In other words, on API < 23, only the DT_NEEDED of the library itself (`libb.so` in my case) would be considered. For API >= 23, it's the breadth-first transitive closure of the library *which is being loaded* (`libd.so` in my case). Is this a correct interpretation of what's happening here?

I've also tested this with an actual app using `System.loadLibrary` with the same results, so it's not specific to just a native executable. A related question though; in the context of an app, what does the "main executable" refer to (e.g. when the documentation states "The global group is shared by all libraries and contains the main executable")?

**Comment by rprichard** [comment]
> In other words, on API < 23, only the DT_NEEDED of the library itself (libb.so in my case) would be considered. For API >= 23, it's the breadth-first transitive closure of the library which is being loaded (libd.so in my case). Is this a correct interpretation of what's happening here?

Yes, that sounds about right. I believe this behavior change started with Android M (API 23).

There should be a local group having at least these libraries: libd.so -> liba1.so -> libb.so -> liba2.so. This local group would be used to look up symbols for all of these newly-loaded libraries. The relocation to `a` should find the definition in liba1.so first. (Libraries like libc.so will also be in the local group used to relocate the libraries. libc.so will have already been relocated, and it's in a different linker namespace, but it will be accessible to all of the app libraries over a namespace link from a classloader namespace to the `default` namespace.)

The global group technically contains:
 - the main executable, followed by
 - LD_PRELOAD libraries, then
 - libraries needed by the executable (in BFS order), then
 - libraries loaded by dlopen with RTLD_GLOBAL (also in BFS order). In addition, libraries with DF_1_GLOBAL (-Wl,-z,global) are in the global group.

For looking up relocations, though, the last two bullet points aren't searched (exception: A DF_1_GLOBAL library is always searched, but DF_1_GLOBAL is broken on O-MR1). A future version of Android might add all of these libraries to the global group used for relocation.

dlsym with RTLD_DEFAULT or RTLD_NEXT searches the full global group listed above, as long as the target API >= 23.

It's a bit more complicated because Android N added linker namespaces, so the list of global libraries varies by namespace. e.g. It's filtered to only include libraries accessible from the particular namespace. That tends to exclude most libraries from `/system/lib[64]`, but it always includes the executable and any initial LD_PRELOAD or DF_1_GLOBAL library.

> I've also tested this with an actual app using System.loadLibrary with the same results, so it's not specific to just a native executable.

Yeah, loadLibrary mostly just calls dlopen. IIRC it prepends a "lib" in front of the name, does its own searching, and typically passes an absolute path to dlopen.

> A related question though; in the context of an app, what does the "main executable" refer to (e.g. when the documentation states "The global group is shared by all libraries and contains the main executable")?

The main executable would be `/system/bin/app_process{32,64}`.

**Comment by smeenai** [comment]
Great, thanks for all the details!

> (Libraries like libc.so will also be in the local group used to relocate the libraries. libc.so will have already been relocated, and it's in a different linker namespace, but it will be accessible to all of the app libraries over a namespace link from a classloader namespace to the default namespace.)

What order does libc.so (and other libraries like it) have in the local group? In other words, if one of my libraries defines a symbol with the same name as a libc symbol, which one will the dynamic linker pick?

Another question. https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#changes-to-library-search-order mentions

> With API 22, load order switched from depth-first to breadth-first to fix dlsym(3).

Does that change only affect `dlsym`, or does it have implications for symbol resolution when you `dlopen` a library as well?

**Comment by rprichard** [comment]
> What order does libc.so (and other libraries like it) have in the local group? In other words, if one of my libraries defines a symbol with the same name as a libc symbol, which one will the dynamic linker pick?

The libraries are ordered according to a breadth-first-search walk, starting with the library that's dlopened. (Or the main executable, for a call to exec.) I think libc.so is typically at the end of the DT_NEEDED list because the clang driver implicitly adds it after most other libraries.

For example, suppose we have these libraries and DT_NEEDED dependencies:

 - libapp1.so
    - libapp2.so
       - libapp3.so
          - libc.so
       - libc.so
    - libc.so

If dlopen is called on libapp1.so, and libapp1.so isn't loaded yet, then libapp1.so is relocated using this local group:
 - libapp1.so
 - libapp2.so
 - libc.so
 - libapp3.so

Similarly, libapp2.so and libapp3.so also use this local group, assuming they haven't been loaded yet.

OTOH, if libapp3.so is loaded using a dlopen call for libapp3.so, then it uses a different local group:
 - libapp3.so
 - libc.so

Once a library is loaded, future calls to dlopen don't alter the relocations. Bionic resolves all relocations eagerly. (RTLD_LAZY is equivalent to RTLD_NOW.)

Starting in API 24, the linker partitions app and system libraries into two namespaces and only allows crossing between the namespaces for certain public libraries (e.g. a "namespace link"). Starting in API 26, when linking a library, the local group will only contain the transitive dependencies that are accessible to that library.

e.g. If an app library depends on libandroid.so (public NDK library), and libandroid.so depends on libinput.so (internal system library), then the symbols from libinput.so aren't searched when relocating the app library. They *are* searched for APIs 23..25.

Similarly, for APIs 23..25, if libandroid.so and libinput.so are loaded as a result of calling dlopen on an app library, then I suspect the linker would search the app library's symbols to resolve relocations in the two system libraries. (In practice, these particular libraries might already be loaded before the app gets a chance to load a library.)

Aside: Unfortunately, while inaccessible transitive dependencies aren't searched as of API 26, dependencies of the executable (e.g. app_process{32,64}, which depends on /system/lib[64]/libc++.so) were considered accessible to every library until R. The NDK builds of libc++ put all the symbols into a special std::__ndk1 C++ namespace, though, which helps to prevent unintended use of the system libc++.so (whose ABI may not be stable, and whose symbols are in std::__1 instead).

> > With API 22, load order switched from depth-first to breadth-first to fix dlsym(3).
>
> Does that change only affect dlsym, or does it have implications for symbol resolution when you dlopen a library as well?

dlsym and relocation symbol lookup seem to have always been fairly independent. AFAICT, the loader never really did a "depth-first" search exactly -- instead, it tended to search only the immediate library or its immediate DT_NEEDED dependencies.

It appears that dlsym on a library handle (not RTLD_NEXT, RTLD_DEFAULT, or the executable) previously searched just that library, but it switched to a BFS search starting in API 21:
 - https://android.googlesource.com/platform/bionic/+log/refs/heads/lollipop-dev
 - https://android.googlesource.com/platform/bionic/+/422106a24d620af4be58e8d92a2e9b7b6167b72d

I'm guessing the line in the changes doc was referring to this dlsym CL.

Relocation processing appears to have switched to a BFS search in API 23. The patch for this appeared in the L-MR1 (API 22) branch, but it was quickly reverted. The change is in M (API 23).

This CL is relevant: https://android-review.googlesource.com/c/platform/bionic/+/111627

Commits:
 - https://android.googlesource.com/platform/bionic/+log/refs/heads/lollipop-mr1-dev
 - https://android.googlesource.com/platform/bionic/+/fd2747bb585fc51b5ad56db09c0e9b66c7091a92
 - https://android.googlesource.com/platform/bionic/+/00dce525530c5d26c20750863f3e9890b468787a

**Comment by smeenai** [comment]
Thanks for the super detailed answers – I really appreciate it, and it's super helpful to build up a good mental model of how this works!

> The libraries are ordered according to a breadth-first-search walk, starting with the library that's dlopened. (Or the main executable, for a call to exec.) I think libc.so is typically at the end of the DT_NEEDED list because the clang driver implicitly adds it after most other libraries.

Right, I'd forgotten about the clang driver's default library additions. The ordering makes sense, thanks.

> Once a library is loaded, future calls to dlopen don't alter the relocations. Bionic resolves all relocations eagerly. (RTLD_LAZY is equivalent to RTLD_NOW.)

Out of curiosity, is this something that might be changed in the future? I noticed the clang driver adds `-z now` for Android platforms by default, so most libraries would get eager binding even if the dynamic linker supported lazy binding. I guess full RELRO is a nice benefit of `-z now` as well.

> Aside: Unfortunately, while inaccessible transitive dependencies aren't searched as of API 26, dependencies of the executable (e.g. app_process{32,64}, which depends on /system/lib[64]/libc++.so) were considered accessible to every library until R. The NDK builds of libc++ put all the symbols into a special std::__ndk1 C++ namespace, though, which helps to prevent unintended use of the system libc++.so (whose ABI may not be stable, and whose symbols are in std::__1 instead).

Aha, this might explain some oddities I've seen in the past – thank you. Note that not all libc++/libc++abi symbols are in the versioned namespace (e.g. `__cxa_*`, the fundamental typeinfos, `new`/`delete`, `std::type_info`, `std::exception`, etc.), so there's still a bunch of potential for conflicts.

In that case, how would the symbol resolution precedence between the `libc++_shared.so` that's linked to app libraries and the system `libc++.so` work? In your previous post, you'd mentioned:

> The global group technically contains:
>
> * the main executable, followed by
> * LD_PRELOAD libraries, then
> * libraries needed by the executable (in BFS order), then
> * libraries loaded by dlopen with RTLD_GLOBAL (also in BFS order). In addition, libraries with DF_1_GLOBAL (-Wl,-z,global) are in the global group.
>
> For looking up relocations, though, the last two bullet points aren't searched (exception: A DF_1_GLOBAL library is always searched, but DF_1_GLOBAL is broken on O-MR1). A future version of Android might add all of these libraries to the global group used for relocation.

In this case, would `libc++.so` be part of the global group but not considered for relocation resolution? In other words, if I `dlopen` an app library, there's no chance of it binding against symbols from the system `libc++.so`? (I understand that `dlsym` might still find those symbols.)

> dlsym and relocation symbol lookup seem to have always been fairly independent. AFAICT, the loader never really did a "depth-first" search exactly -- instead, it tended to search only the immediate library or its immediate DT_NEEDED dependencies.
>
> ...

Got it, thanks for all the change links!

**Comment by rprichard** [comment]
> Thanks for the super detailed answers – I really appreciate it, and it's super helpful to build up a good mental model of how this works!

No problem.

> > Once a library is loaded, future calls to dlopen don't alter the relocations. Bionic resolves all relocations eagerly. (RTLD_LAZY is equivalent to RTLD_NOW.)
> 
> Out of curiosity, is this something that might be changed in the future? I noticed the clang driver adds `-z now` for Android platforms by default, so most libraries would get eager binding even if the dynamic linker supported lazy binding. I guess full RELRO is a nice benefit of `-z now` as well.

Looks like that's [D53117](https://reviews.llvm.org/D53117). I don't think we're going to change this? My understanding is that lazy loading would require remapping part of the GOT as read-write after resolving a lazy lookup, which would weaken RELRO. (Or maybe the remapping would be too expensive, so we'd just leave the table read-write all the time.) Either way, I think we want eager binding for security reasons.

> > Aside: Unfortunately, while inaccessible transitive dependencies aren't searched as of API 26, dependencies of the executable (e.g. app_process{32,64}, which depends on /system/lib[64]/libc++.so) were considered accessible to every library until R. The NDK builds of libc++ put all the symbols into a special std::__ndk1 C++ namespace, though, which helps to prevent unintended use of the system libc++.so (whose ABI may not be stable, and whose symbols are in std::__1 instead).
> 
> Aha, this might explain some oddities I've seen in the past – thank you. Note that not all libc++/libc++abi symbols are in the versioned namespace (e.g. `__cxa_*`, the fundamental typeinfos, `new`/`delete`, `std::type_info`, `std::exception`, etc.), so there's still a bunch of potential for conflicts.

Yeah, I had noticed that a bunch of the symbols weren't versioned. Maybe something could go wrong here. OTOH, maybe these symbols have a sufficiently-stable ABI?

I should probably clarify -- this bug only applies to the immediate dependencies of the executable (not the transitive dependencies). The fix for this was https://android-review.googlesource.com/c/platform/bionic/+/1223687.

> In that case, how would the symbol resolution precedence between the `libc++_shared.so` that's linked to app libraries and the system `libc++.so` work? In your previous post, you'd mentioned:
> 
> > The global group technically contains:
> > 
> > * the main executable, followed by
> > * LD_PRELOAD libraries, then
> > * libraries needed by the executable (in BFS order), then
> > * libraries loaded by dlopen with RTLD_GLOBAL (also in BFS order). In addition, libraries with DF_1_GLOBAL (-Wl,-z,global) are in the global group.
> > 
> > For looking up relocations, though, the last two bullet points aren't searched (exception: A DF_1_GLOBAL library is always searched, but DF_1_GLOBAL is broken on O-MR1). A future version of Android might add all of these libraries to the global group used for relocation.
> 
> In this case, would `libc++.so` be part of the global group but not considered for relocation resolution? [...]

Each linker namespace has a different global group ([android_namespace_t::get_global_group](https://android.googlesource.com/platform/bionic/+/22fa3dde076bf6dbe432acdbede7693d0544564e/linker/linker_namespaces.cpp#128)) that is used for relocation lookup. AFAIK, libc++.so hasn't ever been part of any global group. In the future, bionic may start adding RTLD_GLOBAL libraries to the global group for a namespace, but it wouldn't add libc++.so to the app namespace's global group.

Some modules are special and are inserted into every namespace and into every namespace's global group:

 - the executable
 - LD_PRELOAD libraries
 - transitive dependencies of the executable that are marked DF_1_GLOBAL

These modules' symbols are always searched first for any relocation.

> [...] In other words, if I `dlopen` an app library, there's no chance of it binding against symbols from the system `libc++.so`? (I understand that `dlsym` might still find those symbols.)

The trouble is that relocation lookup (and usually dlsym) also search a local group. If the app depends on (say) liblog.so and/or libandroid.so, which frequently depend on libc++.so, then the app could use libc++.so's symbols via the local group in APIs 23..29.

I would think the BFS ordering would usually find an app's STL symbol before it reaches libc++.so, though. If the app library passed to dlopen has a DT_NEEDED entry for libc++_shared.so, then libc++_shared.so will always take precedence over libc++.so. (Maybe using -Wl,--as-needed could remove a DT_NEEDED entry for libc++_shared.so.)

**Comment by smeenai** [comment]
> > > Aside: Unfortunately, while inaccessible transitive dependencies aren't searched as of API 26, dependencies of the executable (e.g. app_process{32,64}, which depends on /system/lib[64]/libc++.so) were considered accessible to every library until R. The NDK builds of libc++ put all the symbols into a special std::__ndk1 C++ namespace, though, which helps to prevent unintended use of the system libc++.so (whose ABI may not be stable, and whose symbols are in std::__1 instead).
> > 
> > 
> > Aha, this might explain some oddities I've seen in the past – thank you. Note that not all libc++/libc++abi symbols are in the versioned namespace (e.g. `__cxa_*`, the fundamental typeinfos, `new`/`delete`, `std::type_info`, `std::exception`, etc.), so there's still a bunch of potential for conflicts.
> 
> Yeah, I had noticed that a bunch of the symbols weren't versioned. Maybe something could go wrong here. OTOH, maybe these symbols have a sufficiently-stable ABI?
> 
> I should probably clarify -- this bug only applies to the immediate dependencies of the executable (not the transitive dependencies). The fix for this was https://android-review.googlesource.com/c/platform/bionic/+/1223687.

Got it, thanks. Yeah, I'd imagine the symbols not in the versioning namespace should be pretty stable in general, but e.g. libc++ recently gained the ability to do loose typinfo comparisons (typeinfo name string comparisons instead of pointer comparisons) in https://github.com/llvm/llvm-project/commit/2405bd689815, and the commit message mentions making ELF typeinfo comparisons loose by default. That hasn't happened yet, but if it did, it wouldn't necessarily be an ABI break (depending on how change is handled), but you'd still potentially have two functions with the same name with differing behavior (if one libc++ was built with loose typeinfo comparisons and one with strict).

> > In that case, how would the symbol resolution precedence between the `libc++_shared.so` that's linked to app libraries and the system `libc++.so` work? In your previous post, you'd mentioned:
> > > The global group technically contains:
> > > 
> > > * the main executable, followed by
> > > * LD_PRELOAD libraries, then
> > > * libraries needed by the executable (in BFS order), then
> > > * libraries loaded by dlopen with RTLD_GLOBAL (also in BFS order). In addition, libraries with DF_1_GLOBAL (-Wl,-z,global) are in the global group.
> > > 
> > > For looking up relocations, though, the last two bullet points aren't searched (exception: A DF_1_GLOBAL library is always searched, but DF_1_GLOBAL is broken on O-MR1). A future version of Android might add all of these libraries to the global group used for relocation.
> > 
> > 
> > In this case, would `libc++.so` be part of the global group but not considered for relocation resolution? [...]
> 
> Each linker namespace has a different global group ([android_namespace_t::get_global_group](https://android.googlesource.com/platform/bionic/+/22fa3dde076bf6dbe432acdbede7693d0544564e/linker/linker_namespaces.cpp#128)) that is used for relocation lookup. AFAIK, libc++.so hasn't ever been part of any global group. In the future, bionic may start adding RTLD_GLOBAL libraries to the global group for a namespace, but it wouldn't add libc++.so to the app namespace's global group.
> 
> Some modules are special and are inserted into every namespace and into every namespace's global group:
> 
> * the executable
> * LD_PRELOAD libraries
> * transitive dependencies of the executable that are marked DF_1_GLOBAL
> 
> These modules' symbols are always searched first for any relocation.

Got it, thanks.

> > [...] In other words, if I `dlopen` an app library, there's no chance of it binding against symbols from the system `libc++.so`? (I understand that `dlsym` might still find those symbols.)
> 
> The trouble is that relocation lookup (and usually dlsym) also search a local group. If the app depends on (say) liblog.so and/or libandroid.so, which frequently depend on libc++.so, then the app could use libc++.so's symbols via the local group in APIs 23..29.
> 
> I would think the BFS ordering would usually find an app's STL symbol before it reaches libc++.so, though. If the app library passed to dlopen has a DT_NEEDED entry for libc++_shared.so, then libc++_shared.so will always take precedence over libc++.so. (Maybe using -Wl,--as-needed could remove a DT_NEEDED entry for libc++_shared.so.)

Ah, right. I don't remember the details of what I was seeing at this point, but we were building with `-Wl,--as-needed`, so it's possible the DT_NEEDED for libc++_shared.so got dropped and then the transitive BFS search just happened to find the system libc++.so first.

I think that answers all my questions :) Thanks for all the help!

**Comment by Jhons363** [comment]
> > In other words, on API < 23, only the DT_NEEDED of the library itself (libb.so in my case) would be considered. For API >= 23, it's the breadth-first transitive closure of the library which is being loaded (libd.so in my case). Is this a correct interpretation of what's happening here?
> 
> Yes, that sounds about right. I believe this behavior change started with Android M (API 23).
> 
> There should be a local group having at least these libraries: libd.so -> liba1.so -> libb.so -> liba2.so. This local group would be used to look up symbols for all of these newly-loaded libraries. The relocation to `a` should find the definition in liba1.so first. (Libraries like libc.so will also be in the local group used to relocate the libraries. libc.so will have already been relocated, and it's in a different linker namespace, but it will be accessible to all of the app libraries over a namespace link from a classloader namespace to the `default` namespace.)
> 
> The global group technically contains:
> 
> * the main executable, followed by
> * LD_PRELOAD libraries, then
> * libraries needed by the executable (in BFS order), then
> * libraries loaded by dlopen with RTLD_GLOBAL (also in BFS order). In addition, libraries with DF_1_GLOBAL (-Wl,-z,global) are in the global group.
> 
> For looking up relocations, though, the last two bullet points aren't searched (exception: A DF_1_GLOBAL library is always searched, but DF_1_GLOBAL is broken on O-MR1). A future version of Android might add all of these libraries to the global group used for relocation.
> 
> dlsym with RTLD_DEFAULT or RTLD_NEXT searches the full global group listed above, as long as the target API >= 23.
> 
> It's a bit more complicated because Android N added linker namespaces, so the list of global libraries varies by namespace. e.g. It's filtered to only include libraries accessible from the particular namespace. That tends to exclude most libraries from `/system/lib[64]`, but it always includes the executable and any initial LD_PRELOAD or DF_1_GLOBAL library.
> 
> > I've also tested this with an actual app using System.loadLibrary with the same results, so it's not specific to just a native executable.
> 
> Yeah, loadLibrary mostly just calls dlopen. IIRC it prepends a "lib" in front of the name, does its own searching, and typically passes an absolute path to dlopen.
> 
> > A related question though; in the context of an app, what does the "main executable" refer to (e.g. when the documentation states "The global group is shared by all libraries and contains the main executable")?
> 
> The main executable would be `/system/bin/app_process{32,64}`.
