### ISSUE TITLE
[FR] Change priority of std::thread created via ndk - Contrary behaviour JAVA and NDK

### ISSUE THREAD

**Issue by Consti10** [android/ndk#1255]
Description of what the problem is:
You can assign different priorities to Threads created via the java runtime using `Thread.currentThread().setPriority();` . However, no similar functionality exists for threads created in
the ndk (e.g. `new std::thread()` ).  This behaviour is contrary and lead to the misbelieve that calling linux `setpriority` changes the current thread's behaviour [example](https://stackoverflow.com/questions/17398075/change-native-thread-priority-on-android-in-c-c)
While in fact it changes the current process' priority.

Solution:
A possible solution would be to properly implement linux `pthread_setschedparam()`. I'd also be interested in some documentation how ndk threads are created & executed.

**Comment by enh-google** [comment]
the answer from fadden on that stackoverflow post is exactly correct. (as you'd expect, since he wrote most of this in the first place.)

pthread_setschedparam(3) works fine --- you just don't have permission as an app to make changes.

note also that Linux's setpriority behavior with respect to threads vs processes is not the same as POSIX, and Android just inherits the Linux behavior: http://man7.org/linux/man-pages/man2/setpriority.2.html

the `androidSetThreadPriority` that's used internally to implement the Java android.os.Process#setThreadPriority call actually does more than just call setpriority(2) though. it calls some internal APIs that aren't directly exposed in the NDK.

i think the games SDK folks are working on some kind of public thread priority API, so i'll see if i can get them to comment. but right now, if you want the exact android.os.Process#setThreadPriority() behavior for a thread created by std::thread, i'm afraid you'll have to attach it at least temporarily and use JNI.

**Comment by Consti10** [comment]
I'l have to read more to fully understand your answer. In the meantime, regarding
_i'm afraid you'll have to attach it at least temporarily and use JNI._
Does this mean I can just implement a simple cpp 'setThreadPriority' function myself that
_a)_ attaches JVM to current thread
_b)_ calls `android.os.Process#setThreadPriority()` via jni
_c)_ detaches the JVM from the Thread ?

**Comment by enh-google** [comment]
> I'l have to read more to fully understand your answer. In the meantime, regarding
> _i'm afraid you'll have to attach it at least temporarily and use JNI._
> Does this mean I can just implement a simple cpp 'setThreadPriority' function myself that
> _a)_ attaches JVM to current thread
> _b)_ calls `android.os.Process#setThreadPriority()` via jni
> _c)_ detaches the JVM from the Thread ?

correct. that's the best workaround i can think of, and even if we did get an NDK API into S (it's already too late for R), that wouldn't be much use to you as an app author for several years anyway...

**Comment by DanAlbert** [comment]
> even if we did get an NDK API into S (it's already too late for R), that wouldn't be much use to you as an app author for several years anyway...

But making that a jetpack API that does the workaround for you when necessary could be an option.

**Comment by Consti10** [comment]
First: The workaround described by @enh-google seems to work.
I have also validated that when detaching the VM and then re-attaching it the Thread priority set by either `android.os.Process#setThreadPriority()` and `Thread.currentThread().setPriority()` is persistent.
Here is the cpp code:
```
// calls android.os.Process.setThreadPriority()
    static void setProcessThreadPriority(JNIEnv* env,int wantedPriority){
        jclass jcProcess = env->FindClass("android/os/Process");
        jmethodID jmSetThreadPriority=env->GetStaticMethodID(jcProcess,"setThreadPriority","(I)V");
        env->CallStaticVoidMethod(jcProcess,jmSetThreadPriority,(jint)wantedPriority);
    }
 // calls android.os.Process.getThreadPriority(android.os.Process.myTid())
    static void printProcessThreadPriority(JNIEnv* env){
        jclass jcProcess = env->FindClass("android/os/Process");
        jmethodID jmGetThreadPriority=env->GetStaticMethodID(jcProcess,"getThreadPriority","(I)I");
        jmethodID jmMyTid=env->GetStaticMethodID(jcProcess,"myTid","()I");
        jint myTid=env->CallStaticIntMethod(jcProcess,jmMyTid);
        jint currentPrio=env->CallStaticIntMethod(jcProcess,jmGetThreadPriority,(jint)myTid);
        LOGD("printProcessThreadPriority %d",currentPrio);
    }
```
And a short example code to test it:
```
 static void doSomething2(JavaVM* jvm,int prio) {
        JNIEnv* env=attachThread(jvm);
        printProcessThreadPriority(env);
        setProcessThreadPriority(env,prio);
        printProcessThreadPriority(env);
        detachThread(jvm);

        env=attachThread(jvm);
        printProcessThreadPriority(env);
        detachThread(jvm);
    }
 static void test(JNIEnv* env){
        JavaVM* jvm;
        env->GetJavaVM(&jvm);
        std::thread* thread1=new std::thread(doSomething2,jvm,-20);
    }
```
This produces the following output:
```
printProcessThreadPriority -10
printProcessThreadPriority -20
printProcessThreadPriority -20
```
Leading me to believe:
a) when a ndk thread is created it has a default priority of -10 ( which is pretty high) 
b) you can attach & detach the JVM to change the priority of a NDK thread
c) even increasing the priority to -20 (highest) works , but is not recommended
[Full source code](https://github.com/Consti10/LiveVideo10ms/blob/master/VideoTelemetryShared/Helper/NDKThreadHelper.hpp)

**Comment by Consti10** [comment]
However I am still confused what exactly setting the thread priority on android does.
For example, this thread [difference between Thread and Process setPriority](https://stackoverflow.com/questions/5198518/whats-the-difference-between-thread-setpriority-and-android-os-process-setthr)
Claims that Thread.setPriority does the same as Process.setThreadPriority in a different scale.
And there are some more resources indicating that. However, when I change the priority via `Process.setThreadPriority` the value returned by `Thread.currentThread().getPriority()` stays the same.

**Comment by Consti10** [comment]
> > even if we did get an NDK API into S (it's already too late for R), that wouldn't be much use to you as an app author for several years anyway...
> 
> But making that a jetpack API that does the workaround for you when necessary could be an option.

How would that work ? Using prefab ? I am really looking forward for it coming out of beta.

**Comment by enh-google** [comment]
re: Thread.setPriority vs Process.setThreadPriority, the former is _supposed_ to be mapped into the latter behind the scenes, but i know they've had bugs there before, and a quick glance at the code suggests that they currently have their own _copy_ of the code that implements Process.setThreadPriority rather than calling it.

personally, i'd always use the real thing, but, yeah, Thread.setPriority calls _should_ get mapped to corresponding Process.setThreadPriority ones.

**Comment by psiha** [comment]
Why/how is this closed/completed?
We still have no efficient/non-hacky/native way of changing thread priorities?

> pthread_setschedparam(3) works fine --- you just don't have permission as an app to make changes.

Yet we can circumvent this lack of permission by going through JNI? How is this not broken?

**Comment by DanAlbert** [comment]
> Why/how is this closed/completed?

Because this is the wrong place to ask for APIs. We're only the delivery mechanism. You need to file a framework bug on http://b.android.com.

**Comment by yabinc** [comment]
I think pthread_setschedparam() will not be allowed to be set in app processes. Because it can set a process to be real-time process, and starve other processes. As in https://man7.org/linux/man-pages/man3/pthread_setschedparam.3.html.

I also think setprioprity() should work. I found Thread.setPriority() would eventually call setprioprity(), as in https://cs.android.com/android/platform/superproject/+/master:system/libartpalette/palette_android.cc;drc=62a90dc5924a743f06a4c9239b22ef369a81ddf7;l=70.

> This behaviour is contrary and lead to the misbelieve that calling linux setpriority changes the current thread's behaviour [example](https://stackoverflow.com/questions/17398075/change-native-thread-priority-on-android-in-c-c)
While in fact it changes the current process' priority.

I think this understanding is not correct. In linux kernel, it uses light weight process for thread. So if linux kernel says process, it actually means thread. If linux kernel says thread group, it actually means process.
So setpriority(PRIO_PROCESS) does only change the priority of the current thread.
To verify it, I wrote a small program:

`#include <stdio.h>
#include <sys/resource.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <unistd.h>

#include <thread>

using namespace std;

#if !defined(__ANDROID__) && !defined(ANDROID_HOST_MUSL)
static inline int gettid() {
  return syscall(__NR_gettid);
}
#endif

int get_prio() {
  return getpriority(PRIO_PROCESS, gettid());
}

void set_prio(int new_prio) {
  rlimit rlim;
  int result = getrlimit(RLIMIT_NICE, &rlim);
  printf("getlimit result = %d, cur = %lu, max = %lu\n", result, (unsigned long)rlim.rlim_cur,
         (unsigned long)rlim.rlim_max);
  // cur should be 40 to support setpriority -20.
  int ret = setpriority(PRIO_PROCESS, gettid(), new_prio);
  printf("setpriority ret = %d\n", ret);
}

void inherit_priority() {
  for (int i = 0; i < 5; i++) {
    printf("inherit thread %d: priority = %d\n", gettid(), get_prio());
    sleep(1);
  }
}

void update_priority() {
  printf("update thread %d: priority = %d\n", gettid(), get_prio());
  printf("update thread %d, set prio to %d\n", gettid(), -20);
  set_prio(-20);
  thread t(inherit_priority);
  for (int i = 0; i < 5; i++) {
    printf("update thread %d: priority = %d\n", gettid(), get_prio());
    sleep(1);
  }
  t.join();
}

int main() {
  printf("main thread %d: priority = %d\n", gettid(), get_prio());
  thread t(update_priority);
  for (int i = 0; i < 5; i++) {
    printf("main thread %d: priority = %d\n", gettid(), get_prio());
    sleep(1);
  }

  t.join();
}`

I run the program in a debuggable app context via run-as. The output is below:
oriole:/data/user/0/com.example.android.displayingbitmaps $ ./simpleperf_setpriority64                                                                                      
main thread 26920: priority = 0
main thread 26920: priority = 0
update thread 26921: priority = 0
update thread 26921, set prio to -20
getlimit result = 0, cur = 40, max = 40
setpriority ret = 0
update thread 26921: priority = -20
inherit thread 26922: priority = -20
main thread 26920: priority = 0
update thread 26921: priority = -20
inherit thread 26922: priority = -20
main thread 26920: priority = 0
inherit thread 26922: priority = -20
update thread 26921: priority = -20
main thread 26920: priority = 0
inherit thread 26922: priority = -20
update thread 26921: priority = -20
main thread 26920: priority = 0
update thread 26921: priority = -20
inherit thread 26922: priority = -20

It shows setpriority() works in the app context, and it only affects the thread you called setpriority() for, and new threads created from it.

**Comment by enh-google** [comment]
"what he said".

i also think pthread_setschedprio() should work too, if you don't want to do the gettid()/pthread_gettid_np() stuff yourself.

pthread_setschedprio() will call sched_setparam() which actually only sets the priority. (as opposed to pthread_setschedparam() which will call sched_setscheduler() and fail because you're not allowed to do that --- confusing, no? who comes up with these names?)

**Comment by enh-google** [comment]
( https://android-review.googlesource.com/c/platform/bionic/+/2441524 documents this in <pthread.h> directly.)

**Comment by DanAlbert** [comment]
Thanks for help clearing up that confusion, @yabinc!

One thing to note if you need to set the priority of something other than the current thread, `pthread_setschedprio` was added in API 28, so you still will need to go through JNI if you want it to work on older devices.

**Comment by yabinc** [comment]
Surprisingly, when I tried to test pthread_setschedprio(), it didn't work.
I found pthread_setschedprio() is implemented by sched_setparam(). From https://man7.org/linux/man-pages/man2/sched_setparam.2.html:
  The value param->sched_priority must lie
       within the range given by [sched_get_priority_min(2)](https://man7.org/linux/man-pages/man2/sched_get_priority_min.2.html) and
       [sched_get_priority_max(2)](https://man7.org/linux/man-pages/man2/sched_get_priority_max.2.html).

From kernel code in https://github.com/torvalds/linux/blob/master/kernel/sched/core.c#L8881, the min and max priority of SCHED_NORMAL are both 0.
So For not real time threads, we can't set any value other than 0.
I think both pthread_setschedprio() and pthread_setschedparam() are for real time threads. We can document that.

Other possible functions besides setpriority() are:
nice() - which actually calls setpriority(), and only sets priority for the current thread and inherited threads.
I feel sched_setattr() is likely to work, by setting sched_nice value. But I didn't test it. It seems much more complex to use, and doesn't have pthread wrapper function.

**Comment by enh-google** [comment]
> Surprisingly, when I tried to test pthread_setschedprio(), it didn't work.

yeah, confirmed in a sample app. i've updated my comment above (and will redo the suggested header change).

> I think both pthread_setschedprio() and pthread_setschedparam() are for real time threads. We can document that.

yeah, i think you're right. i think the key point is (https://man7.org/linux/man-pages/man7/sched.7.html):

       For threads scheduled under one of the normal scheduling policies
       (SCHED_OTHER, SCHED_IDLE, SCHED_BATCH), sched_priority is not
       used in scheduling decisions (it must be specified as 0).

SCHED_OTHER -- also known as SCHED_NORMAL -- is what app threads are using. (which is just the documentation version of what you were saying about the kernel source :-) )

> I feel sched_setattr() is likely to work, by setting sched_nice value. But I didn't test it. It seems much more complex to use, and doesn't have pthread wrapper function.

or even a non-pthread wrapper function; anyone using that needs to use syscall(3).

given all this, i'll refer to setpriority() in the docs (and explain that the pthread functions are only useful for SCHED_RR and SCHED_FIFO).
