### ISSUE TITLE
[BUG] LOCAL_FILTER_ASM := cp - broken with clang

### ISSUE THREAD

**Issue by DmitryYudin** [android/ndk#1263]
This bug was also reported here: https://groups.google.com/forum/#!msg/android-ndk/ZXC0zy5JkJI/nEJcWPheBQAJ as appeared after switching from `gcc` to `clang`.

Clang does not recognize generated assembly as an input:
``` text
[arm64-v8a] Assembly       : mylib <= foo.filtered.s
clang: warning: argument unused during compilation: '-MMD' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-MP' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-MF .build_ndk/local/arm64-v8a/objs/mylib/./src/foo.o.d' [-Wunused-command-line-argument]
.build_ndk/local/arm64-v8a/objs/mylib/./src/foo.filtered.s:3:26: error: expected comdat type such as 'discard' or 'largest' after protection bits
        .section        .text.foo,"ax",@progbits
                                       ^
.build_ndk/local/arm64-v8a/objs/mylib/./src/foo.filtered.s:6:8: error: expected absolute expression
        .type   foo,@function
                ^
```

**Comment by DanAlbert** [comment]
I'm pretty sure this is just a case where the assembly needs to be updated since the two dialects are not identical, but I don't speak asm so maybe @enh-google can confirm.

**Comment by enh-google** [comment]
grep of llvm suggests this is an error from the *COFF* code, not the ELF code!

NDK r21's clang assembles a .s file containing those directives fine for me, so you'll have to share a reproducible case (and i'll reopen if you do so). my guess, though, is that you've done something to the compiler flags that means you're accidentally targeting *Windows* rather than Android?
