### ISSUE TITLE
Does R21 libc++ support full features of C++17?

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1272]
https://developer.android.com/ndk/guides/cpp-support  says libc++ supports C++17. But earlier when we were using R16, we found many features of C++17 were not implemented. Even with NDK R21B, we found filesystem not supported by libc++ and the same is confirmed in https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md#package-management . 

So I want to know the extent to which libc++ supports C++17. Please let me know the percentage of C++17 features implemented by libc++ (rough percentage is fine).

Thanks!!

**Comment by DanAlbert** [comment]
No, C++17 isn't finished in libc++ anywhere: http://libcxx.llvm.org/cxx1z_status.html

`std::filesystem` is https://github.com/android/ndk/issues/609

**Comment by pendyalasyam** [comment]
Thanks @DanAlbert !!

**Comment by DanAlbert** [comment]
Longer answer since I'm at a real keyboard this time :)

It's far from perfect since all that tells you is what upstream claims support for at the time of the last doc update. I think they're pretty good at updating it when they finish features, so shouldn't be too far off from the truth for upstream. It's also the source of truth for the current HEAD of libc++, so it almost certainly is ahead of whatever NDK someone happens to be using.

Honestly, the best way to answer the question of "is `std::whatever` supported in NDK rX?`" is to try it and see. The changelogs do publish the revision of libc++ used for each release, so you could always follow that link to get to the source for that page at the revision in question. For example, r22's changelog links to https://github.com/llvm/llvm-project/commit/52ec983895436089c5be0b0c4d967423db16045b, and from there you could navigate to https://github.com/llvm/llvm-project/blob/52ec983895436089c5be0b0c4d967423db16045b/libcxx/www/cxx1z_status.html. That seems like more work to me, but I suppose it's useful as a sanity check :)

@enh-google sent a patch to link the upstream doc in the C++ support doc you referenced, btw.
