### ISSUE TITLE
[FR] CMake update

### ISSUE THREAD

**Issue by tobrun** [android/ndk#1278]
Was wondering about any plans to update CMake to a newer version. 
[Current stable version](https://cmake.org/download/) is `3.17.3`, while android tooling supports `3.10.2` or `3.6.4111459`.

**Comment by DanAlbert** [comment]
It's in progress, but this isn't something our team is responsible for.

**Comment by kkaefer** [comment]
@DanAlbert Can you please point us to more information on when/how this will happen?

**Comment by DanAlbert** [comment]
Seems all the public bugs got duped into the internal one, annoyingly (though I think since the changes are all to an internal branch anyway nothing of interest would be visible in a public bug). https://issuetracker.google.com/152330182 is probably the best place to comment. I reopened and marked it as blocked rather than a dup so the closure state will at least be reflected properly.

There isn't really any of the info you're looking for in the internal bug, fwiw. Changes are going in to support the new non-server CMake server API, and it isn't done yet. A summary of the progress is probably "working on it, done soon but don't know how soon".
