### ISSUE TITLE
[FR] Secure key management (keyctl)

### ISSUE THREAD

**Issue by borrrden** [android/ndk#1284]
**Is your feature request related to a problem? Please describe.**
I'd like a way to generate asymmetric keys in a way that the private bits are never visible to the entity requesting their creation.  This happens via the trusted platform module, which the Android KeyStore Java implementation makes use of but I don't see an NDK counterpart.  

**Describe the solution you'd like**
Access to the keyctl interface, and ideally the keyutilities library (`/system/lib64/libkeyutilities.so` on recent builds).  

**Describe alternatives you've considered**
I tried using pure syscalls to achieve this but that was a slow and not very fruitful process.

**Comment by enh-google** [comment]
libkeyutils is literally just a bunch of one-liners calling syscall(3). for example: 
```
key_serial_t add_key(const char* type, const char* description, const void* payload,
                     size_t payload_length, key_serial_t ring_id) {
  return syscall(__NR_add_key, type, description, payload, payload_length, ring_id);
}
```

https://android.googlesource.com/platform/system/core/+/refs/heads/master/libkeyutils/keyutils.cpp

it doesn't seem like this warrants inclusion in the NDK.

**Comment by snej** [comment]
Copying and pasting source code out of internal system libraries does not seem like a solid way to do this. What happens if that implementation changes in the future?

**Comment by enh-google** [comment]
it's a kernel ABI, so it's not changing in any way.

**Comment by DanAlbert** [comment]
To clarify, what's the motivation for not using the Java API? I assume it's not a performance concern because I'm guessing the cost of this API would make that negligible. Are you trying to port code from a different system that uses these APIs?

I'm not very familiar with keyctl or the Android keystore APIs, so I'm also not sure if there are Android-specific concerns that would make keyctl an unhelpful fit for this use case.

If a bad fit for the NDK but still potentially useful, you could probably fairly simply make an AAR out of the upstream keyutils.

**Comment by enh-google** [comment]
> I'm not very familiar with keyctl or the Android keystore APIs, so I'm also not sure if there are Android-specific concerns that would make keyctl an unhelpful fit for this use case.

yeah, just to clarify: it is my belief that the keyctl stuff _isn't_ really relevant. it's just _a_ possible back end.

sounds like dan's going to find someone who works on this stuff to take a look at the higher-level question https://groups.google.com/g/android-ndk/c/rBFpP2AGNRE/discussion 

if those folks come back and say, that this is the one true back end then i'll add the header tomorrow :-) but right now i'm assuming this would just be misleading.

(i'm not even sure you can use this stuff from an app context anyway. the "tests" i wrote for the internal libkeyutils are shockingly perfunctory, and that's not [just] because i'm a terrible person --- i'm pretty sure i remember failing to write decent tests. that's also why i haven't made much progress implementing keyctl(1) for toybox, which is also on my to-do list. but it's possible that's just a historical accident, where the library was needed before we had kernels that supported it. iirc only Intel was using it at the time i added it?)

**Comment by DanAlbert** [comment]
(reopening until we have a more certain answer)

**Comment by borrrden** [comment]
At the end of the day, is there something available in the NDK to make use of the hardware backed key storage?  If there is then I won't need keyctl specifically (I noticed older Androids have libkeystore_binder?  Is that something relevant?)  Everything I've read about Linux points me to keyctl for this, but I am not an expert.  

The main reason I don't want to use Java is that I am writing a multi platform C++ library which uses OS specific APIs for doing this (For example, Keychain on iOS and NCrypt on Windows).  It has no knowledge of the JNI at this level (there is another library that links with it that adds JNI stuff on top of it to keep it clean).  We have come up with a method of callbacks that allow us to accomplish this but I feel like it would be much cleaner if I could skip all that and just do this in the NDK directly.  There must be some form of C or C++ call that will interact with the storage right?

**Comment by DanAlbert** [comment]
> At the end of the day, is there something available in the NDK to make use of the hardware backed key storage?

Well, I was checking to see if `keyctl(2)` was covered by CTS, and technically it is, but in exactly the opposite way from what you're hoping: https://cs.android.com/android/platform/superproject/+/master:cts/hostsidetests/seccomp/app/gen_blacklist.py;l=43;drc=93bc74b258b248ac4a80085d164b64841eb49e41

So `keyctl(2)` is not usable on newer devices because seccomp prevents it. Aside from that, there aren't other APIs for this in the NDK currently. I sent an email to the person that owns the Android keystore implementation to get his opinion.

@enh-google might also have some architecture suggestions, but I'm too much of a JNI noob to be of much use there :)

**Comment by borrrden** [comment]
Honestly I might even be mistaken on the purpose of keyctl.  It appears to not do the one thing I want it to do:  Generate a private key without showing me and give me an opaque handle to it.  Maybe the Linux kernel simply doesn't have this functionality after all, which is too bad....it also makes me more curious about how the Java based Android KeyStore accomplishes its goals.

**Comment by enh-google** [comment]
yeah, keyctl is not what you want. not what anyone wants, really, with the possible exception of toybox, and i'll just use syscall() there. "how the Java stuff works" is an implementation detail that's changed at least once, i think. the Java API is the only public API right now, and -- even though a corresponding C API might be a good idea, and dan's passed that on to the relevant team -- even if they do decide to add one, it wouldn't be available until the 2021 Android release. and i'm assuming you're not working on an app whose minSdkVersion is _next_ year's :-)

this is why i'm so strongly against adding the keyctl wrappers --- the only people who need them either already have libkeyutils (because they're part of the system) or will just want to use syscall() directly (because, like toybox, they don't want random dependencies _and_ need to work on other OSes that use the Linux kernel, not just Android). in cases where i've added such niche stuff before, i've come to regret it because it's confused more people than it's helped.

**Comment by borrrden** [comment]
[This](https://github.com/aosp-mirror/platform_hardware_libhardware/blob/master/include/hardware/keymaster2.h) appears to be what I'm after.  The Keymaster HAL.  This is what actually does the key generation in such a way that the material is not visible to the person requesting it right?

**Comment by enh-google** [comment]
that's an internal API between the generic Android parts of the system and the SoC vendor/OEM-provided parts.

the  Java API is the public API for apps.

**Comment by borrrden** [comment]
Ok, thanks for clearing things up!  I'll keep going with the planned architecture of registering callbacks from another library that call into JNI to use the Java AndroidKeyStore class.  I think there is nothing else needed for this ticket.

**Comment by enh-google** [comment]
> I think there is nothing else needed for this ticket.

...other than a good book that explains how all the parts of the system work and interact!

i dread to think how thick that book would be at this point though :-(
