### ISSUE TITLE
[BUG] [simpleperf] CppApi in-app recording only records a sub set of events requested

### ISSUE THREAD

**Issue by xorange** [android/ndk#1285]
## Description

I'm trying to use simpleperf to record a block of native C++ code.
I'm refering to `https://android.googlesource.com/platform/system/extras/+/master/simpleperf/demo/README.md#profile-via-app_api` to build up my perf record code and workflow.

Everything works and I succeed in the following workflow:
1. `python scripts\api_profiler.py prepare`
2. run code on device
3. `python scripts\api_profiler.py collect -p <myapp>`
4. `python scripts\report_html.py --aggregate-by-thread-name --add_disassembly --ndk_path <my_ndk_path> -i <newly_pulled_perf.data in step 3>`

The problem came up when I try to record multiple events. I did this by the following:

First I modified `simpleperf.cpp`, which was downloaded from  `https://android.googlesource.com/platform/system/extras/simpleperf/app_api/cpp` and served as an example.

The modification was to include multiple events separated by comma '`,`' in argument `-e`
(A more illustrative screenshot would be provided below)
```
RecordOptions& RecordOptions::SetEvents(const std::vector<std::string> &events) {
    if (events.size() == 0)
    {
        impl_->event = "cpu-cycles";
    }
    else
    {
        impl_->event = events[0];
        for (auto e =  events.begin() + 1; e != events.end(); ++e)
        {
            impl_->event += "," + *e;
        }
    }
    return *this;
}
```

And I called it with the following events strings:
```
std::vector<std::string> perf_events = {
    "cpu-cycles",
    "cache-references",
    "cache-misses",
    "raw-inst-retired",
    "raw-ase-spec",
    "raw-l1d-cache",
    "raw-l1d-cache-refill",
    "raw-l1d-tlb",
    "raw-dtlb-walk",
    "dTLB-load-misses",
    "cpu-clock",
};
```

But `python scripts\report_html.py` gives me the incomplete output:
[report.html screenshot](https://drive.google.com/file/d/1SG5yzjiatMiZKqUjN-wNfbehvKwFYiTZ/view?usp=sharing)

In case something goes wrong with the screenshot, the report.html gives the Record Cmdline as below:
```
/data/data/<myapp>/simpleperf record --stdio-controls-profiling --in-app --tracepoint-events /data/local/tmp/tracepoint_events -o perf-06-19-15-25-18.data -e cpu-cycles,cache-references,cache-misses,raw-inst-retired,raw-ase-spec,raw-l1d-cache,raw-l1d-cache-refill,raw-l1d-tlb,raw-dtlb-walk,dTLB-load-misses,cpu-clock -f 16000 -p 19580 -g
```
which has all 11 specified events, while there are only 4 results tab of events given.

## What I've tried

1. I've tried several different set of request events, it seemes that only a maximum of 4 events are supported. Any events more than 4 would encounter this problem.

2. I've tried to record each of the events separately. The 11 events above are guaranteed to be supported on the test device.

3. I've tried to use `perf stat` with more than 4 events and it works fine:
```
./simpleperf stat --app <myapp> -e cpu-cycles,cache-references,cache-misses,raw-inst-retired,raw-ase-spec,raw-l1d-cache,raw-l1d-cache-refill,raw-l1d-tlb,raw-dtlb-walk,dTLB-load-misses,cpu-clock --duration 10         <
Performance counter statistics:

#          count  event_name             # count / runtime,  runtime / enabled_time
     390,238,795  cpu-cycles             # 1.706328 GHz   (40%)
      89,427,875  cache-references       # 377.188 M/sec  (39%)
       2,187,320  cache-misses           # 9.455 M/sec    (40%)
     258,675,883  raw-inst-retired       # 1.240 G/sec    (35%)
         399,775  raw-ase-spec           # 2.138 M/sec    (33%)
      67,316,328  raw-l1d-cache          # 373.874 M/sec  (36%)
       1,498,490  raw-l1d-cache-refill   # 8.413 M/sec    (42%)
      98,485,989  raw-l1d-tlb            # 577.754 M/sec  (38%)
          47,680  raw-dtlb-walk          # 256.215 K/sec  (39%)
       1,369,375  dTLB-load-misses       # 6.827 M/sec    (39%)
  668.948167(ms)  cpu-clock              #                (100%)

Total test time: 10.011877 seconds.
simpleperf W cmd_stat.cpp:863] Percentages < 100% means some events only run a subset of enabled time,
simpleperf W cmd_stat.cpp:863] probably caused by hardware counter multiplexing (less counters than events).
simpleperf W cmd_stat.cpp:863] Try --use-devfreq-counters if on a rooted device.
```

4. I've tried to add debug print in report_html.py, and it showed that indeed only the subset of events existed in the given perf-06-19-15-25-18.data.

5. Not only did `simpleperf stat` works fine, but also did `simpleperf record`. I tried using `simpleperf record` with the same 11 events, and feed the generated perf.data to report_html.py. It works fine.
[using simpleperf record gives the correct output](https://drive.google.com/file/d/1YBaG--4Okeay9HGDhJ4B1DqV3pXpN4Ck/view?usp=sharing)

So I assumed something did not go as expected in `api-prepare` + `record --in-app` + `api-collect` workflow. Only part of the requested events are actually recorded.

## Environment Details

Simpleperf version 1.build.6401870, which comes together with `https://android.googlesource.com/platform/system/extras/simpleperf`, under dir `scripts/bin/android/arm64`

NDK version: 19.2.5345600

Device: SamSung Galaxy S9, Android 9.0

**Comment by yabinc** [comment]
Thanks for the detailed report!

I think the problem is not enough CPU PMU counters to monitor all events. The device may only have 4 counters available for each cpu, like https://android.googlesource.com/platform/system/extras/+/master/simpleperf/doc/android_platform_profiling.md#hardware-pmu-counter-limit. When you try to monitor many hardware events, the counters are multiplexed between events. Each event only uses the counter for a subset of total running time. Although the kernel tries to make a balance, it is totally possible that some events don't get a chance to use a counter. As can be seen in the stat cmd output, only the software event cpu-clock takes 100% running time, hardware events all take < 100% of running time. (The situation is explained in https://android.googlesource.com/platform/system/extras/+/master/simpleperf/doc/executable_commands_reference.md#select-events-to-stat).

For why using api recording fails to record all events:
1) It uses the same cmdline interface as simpleperf record. The only difference is the former is executed from api library, the latter is executed from shell.

2) In the report_html.py report, the record cmdline shows all 11 events are recorded. So simpleperf knows to record all 11 events. To further verify it, you can change --log debug to --log verbose in https://android.googlesource.com/platform/system/extras/+/master/simpleperf/app_api/cpp/simpleperf.cpp#410 to print perf_event_open msgs, like:
  simpleperf V event_selection_set.cpp:492] OpenEventFile for perf_event_file(event cpu-cycles, tid 14824, cpu 0)
simpleperf V event_selection_set.cpp:492] OpenEventFile for perf_event_file(event cpu-cycles, tid 14824, cpu 1)

  It shows which events are opened on which cpus.

3) I don't know why api recording fails but normal recording succeeds. Did you use Pause/Resume recording in api recording interface? If yes, that may be the reason. Each time you resume recording, the events are scheduled on, event 0-3 use counters, and before it timeouts to rotate to the next events, you pause recording. And it loops. As a result, event 0-3 always use counters, and event 4-10 never get a chance to use the counters.

**Comment by xorange** [comment]
Thanks for reply and reasonable suggestions!

No I did not use Pause/Resume. I'm also wondering why api recording fails but normal recording succeeds. Indeed I agree that maybe it has something to do with the way api recording was used, since they shared the same cmdline interface. 

For the record, I called `session.StartRecording(options);` and `session.StopRecording();` in the same thread with my client code, not using pthread as the example suggested. I guessed it's ok for `vfork()` -> `execvp( "simpleperf record --in-app ..." )`. So it's something like:
```
session.StartRecording(options);
// code block to be tested
session.StopRecording();
```
Meanwhile I had trouble understanding the [example](https://android.googlesource.com/platform/system/extras/+/master/simpleperf/demo/CppApi/app/src/main/cpp/native-lib.cpp): Since pthread "ProfileThreadFunc" and "BusyThreadFunc" are not explicitly synchronized, how could one guarantee that the profile result is from the exact lifetime of targeted client?

I'll keep working on it. For matter of this issue, I'm closing now and let me reopen if anything new comes up.

**Comment by yabinc** [comment]
It's fine to use the api in any thread (probably not the UI thread, because it uses a synchronous communication with simpleperf process). The reason to separate api use and workload in the example, is to focus on api use code.

**Comment by xorange** [comment]
> It's fine to use the api in any thread (probably not the UI thread, because it uses a synchronous communication with simpleperf process). The reason to separate api use and workload in the example, is to focus on api use code.

Got it. Thanks.
