### ISSUE TITLE
[DOC] AChoreographer_refreshRateCallback

### ISSUE THREAD

**Issue by Consti10** [android/ndk#1332]
The method `AChoreographer_refreshRateCallback` is listed here [ndk choreographer](https://developer.android.com/ndk/reference/group/choreographer)
But it is missing a specified minapi. It is also not available on minSdkVersion = 29 , e.g the latest sdk version.

**Comment by Consti10** [comment]
Also,as a side note, it would be quite usefull if this callback reports the exact display refresh rate in nanoseconds (respectively the time between VSYNCs ) instead of the 'fake' values reported by the java Choreographer, who always assumes that a 60hz display runs at a refresh rate of 16.6... ms even tough the display might run at 16.4 ms or similar.

**Comment by enh-google** [comment]
> But it is missing a specified minapi.

it's a typedef, so it's "available" regardless. (but the APIs that _use_ it so far are both API level 30.)

> It is also not available on minSdkVersion = 29 , e.g the latest sdk version.

what version of the NDK are you using? note that you need r21d for the final R headers. (i just checked, and this is in r21d but not r21c.)

> Also,as a side note, it would be quite usefull if this callback reports the exact display refresh rate in nanoseconds

you'll want to report that to the graphics folks directly (https://source.android.com/setup/contribute/report-bugs). if you do, paste the bug here and we can try to make sure it gets assigned to the right folks...
