### ISSUE TITLE
How is SSL actually supported in Android

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1345]
Hi Team,

While trying to understand how Android actually supports SSL, I found this article [](https://www.linuxjournal.com/article/10896#:~:text=By%20default%2C%20the%20Android%20platform,as%20a%20faster%20SSL%20implementation.) . As far I understand the article and combine the little knowledge that I have, I understand that Javax.net.ssl package uses SSL implementations like OpenSSL and BoringSSL to provide the security functionality.

1. Is my understanding correct?

Also I read that Android has switched to BoringSSL from OpenSSL starting Marshmallow.

2. So Android supports on BoringSSL currently?

3. Also, is the BoringSSL library supported by Android FIPS 140-2 compliant?

Thanks...

**Comment by enh-google** [comment]
i think you forgot to include your article link.

Android *uses* BoringSSL, but it's not available through the NDK. what's used to implement the Java APIs is implementation defined. "as long as you pass the CTS tests, you can implement it how you like" but in practice, yes, BoringSSL is used for _some_ of the work.

in more recent OS releases the BoringSSL is FIPS certified, but on older OS versions it depends on the OEM. some of them did the FIPS work, but most didn't.

**Comment by pendyalasyam** [comment]
@enh-google , thanks for your reply.

Sorry, I know this NDK forum but I did not find any other which can provide responses faster as this. Please let me know if we have some portal like this to ask AndroidSDK/Java related questions.

So, 
1. By default, does Java security APIs on Android use BoringSSL?
2. From which OS version, BoringSSL is FIPS certified?

**Comment by prbprbprb** [comment]
1. Yes, most of the Java security APIs are backed by BoringSSL via Conscrypt which is the default security `Provider`.  A few less common algorithms are backed by other `Provider`s, e.g. BouncyCastle and Android KeyStore.

2. BoringSSL is currently undergoing FIPS certification and the version being certified is the version that ships with Android 11.    A few devices running Android 10 (basically Pixel only) will get the same FIPS-compatible version as an update, but the devices won't be FIPS certified because of other changes in the OS since 10.

For Android TLS related questions, feel free to open an issue in https://github.com/google/conscrypt or post to https://groups.google.com/g/conscrypt

**Comment by pendyalasyam** [comment]
Thanks @prbprbprb . It cleared my doubts.

**Comment by pendyalasyam** [comment]
@prbprbprb , checking again for confirmation. Is BoringSSL used in Android 11 FIPS validated(certified) ?

**Comment by prbprbprb** [comment]
Yup! Android 11 is the first release with a FIPS certified BoringSSL.

**Comment by pendyalasyam** [comment]
@prbprbprb , thanks for the confirmation.

**Comment by mposch-Z** [comment]
I'm not sure i'm understanding a colleague correctly, but is there a way to enable BoringSSL debug logging to view issues w/ certificate authentication?  I'm working in Android studio on MacOS
