### ISSUE TITLE
[question] Obtaining timezone offset seconds for DST

### ISSUE THREAD

**Issue by sdaly2107** [android/ndk#1367]
Hello

Our unit tests for some DateTime classes uses the function below to obtain the timezone offset so our assertions work on different timezones across different build servers.

In this instance, the time is set correctly and timezone is UK/GMT.  

Timezone offset 0 <-- Correct when isDST is false.
Timezone offset (dst) 1603983356 <- Returned when isDST is true.  Expected 3600.

This is working on Linux and Windows - is there some missing functionality around when tm_isdst is set to 1?...or is there a better way to do this on Android?

```
static int32_t GetTimeZoneOffSetSeconds(bool isDST)
{
    time_t now = time(nullptr);

    std::tm tm{};
#if defined(OS_FAMILY_WINDOWS)
    gmtime_s(&tm, &now);
#else
    gmtime_r(&now, &tm);
#endif

    tm.tm_isdst = isDST ? 1 : 0;
    const time_t localTime = mktime(&tm);
    double diff = difftime(now, localTime);

    return static_cast<int32_t>(diff);
}
```

Thinking it maybe doesn't work because the current date is not DST.  It does however work on Windows and Linux OK.

Thanks
Scott

**Comment by DanAlbert** [comment]
@enh-google in case there's some KI here, but this sure sounds like a device specific issue. What device are you seeing this on? What API level? Have you tried others?

**Comment by sdaly2107** [comment]
This is on an emulator, NDK r20b, API level 26. 

What does work for us is if we move the offset functionality to our DateTime class and basically take the local and utc time for the time the object is holding and diff on them.

Sort of feels like this is failing because today's date (in UK zone is non dst, but the dst flag has been set to 1)...just strange the behaviour is different on Android.

**Comment by enh-google** [comment]
what exactly is persist.sys.timezone (and/or $TZ) set to for you? i can only reproduce this with $TZ set to "GMT", or $TZ unset and persist.sys.timezone set to "GMT" (rather than "Europe/London", which works as you'd expect, as do other Olson ids).

the large value you're seeing is because mktime() is returning -1 and you're not checking that before going into the subtraction that's all difftime() is. this is exactly what you'd see on Linux too if you set TZ=GMT (because GMT != Europe/London --- GMT is a synonym for UTC, and there is no daylight savings variant of that).

the interesting question to me is how you ended up with your time zone set to "GMT" (rather than Europe/London, which is what it should be in Britain)...

**Comment by sdaly2107** [comment]
When I say UK/GMT, I'm meaning any UK based Olson Id and in GMT / not in DST.  

Our unit tests were failing on Android only so there's definitely a difference in behaviour.  We have an alternative way to do this now so will not investigate any further.
