### ISSUE TITLE
[BUG] SIGABRT when throwing extended exceptions across library border

### ISSUE THREAD

**Issue by ViliusSutkus89** [android/ndk#1434]
Hello,

I have a couple of SHARED libraries: thrower and catcher. catcher is linked against thrower. I'm trying to throw an extended exception in thrower library and catch it in the catcher library. The exception looks like this:
```c++
class ExtendedException : public std::runtime_error {
public:
  using std::runtime_error::runtime_error;
};
```
Throwing `std::runtime_error` in thrower and catching it in catcher works fine.
Throwing `ExtendedException` in thrower and catching it in the same library works fine too.
Throwing `ExtendedException` in thrower and trying to catch it in catcher produces SIGABRT (and 0xdeadbaad on Android-16).

[Test case for reproduction](https://github.com/ViliusSutkus89/NDK_Exception_In_Library) - Test case called from in [ExceptionInstrumentedTest.java](https://github.com/ViliusSutkus89/NDK_Exception_In_Library/blob/master/app/src/androidTest/java/com/viliussutkus89/exceptioner/ExceptionInstrumentedTest.java)

Tried to come up with a smaller test case - [ndk-build](https://github.com/ViliusSutkus89/NDK_Exception_In_Library/tree/master/ndk-build-cant-repro), but extended exceptions across library borders seem to work there fine.

It may be somewhat related to the way native libraries are loaded by Java. Failing reproduction case loads dependencies first, and only then catcher is loaded:
```Java
System.loadLibrary("c++_shared");
System.loadLibrary("thrower");
System.loadLibrary("catcher");
```
No SIGABRT if catcher is loaded directly, letting `System` handle all the dependencies. Would be fine by me, but I want to target Android-16 sometimes too, which means dependencies have to be handled manually.

Repro case is targeting Android-30, building with r22.0.7026061, using CMake-3.10.2.
Can repro with r20.1.5948944 too.
Running on emulator - "system-images;android-30;google_apis;x86_64", can repro with "system-images;android-16;default;x86" too, when targeting Android-16.

How do I dig deeper?

**Comment by DanAlbert** [comment]
Sounds like https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md#rtti_exceptions-not-working-across-library-boundaries. If you're not able to add key functions to your exception types they cannot be caught when loading in the manner you describe. Using https://github.com/KeepSafe/ReLinker probably fixes your issues for old devices.

Strange as it sounds, all the pieces are working correctly, but the three things in play here don't work well together. The Itanium C++ ABI says that without a key function the vtable (and typeinfo) need to be emitted in every place they're used, so they must be weak symbols. Weak symbols are merged when they load, which is why this works when you remove the redundant `System.loadLibrary` calls. When they are loaded independently of each other, you're being hit by the fact that `System.loadLibrary` uses `RTLD_LOCAL`, so the typeinfos are all not visible to the later loads, and you end up with distinct copies the typeinfo: one in libthrower.so and one in libcatcher.so. These two typeinfos are not equal since there's no way to prove that the types are actually the same unless they are an identical address (this is also part of the Itanium C++ spec), so the exception is not caught.

Let me know if I've misunderstood and we can reopen.

**Comment by ViliusSutkus89** [comment]
Thanks a lot! I have enough info not only to fix the bug in my code, but also enough pointers to read through to understand how to not run into a situation like this again.
