### ISSUE TITLE
[question]what should i do to build asan in Android?

### ISSUE THREAD

**Issue by boulevarder** [android/ndk#1436]
https://android.googlesource.com/toolchain/llvm_android/+/master/README.md
i use the method in this website, but it take so much time, is there a way to only build asan or make it faster?
thx!!!

**Comment by DanAlbert** [comment]
Not that I know of.

Let's try to keep additional follow ups to this conversation all in this thread. Filing individual bugs is great for actual bugs, but this is essentially an email thread so it just makes it harder to keep the right people on the thread. I'm not closing it because it shouldn't be used, I'm closing it because we don't need to "fix" this in an NDK release.

**Comment by stephenhines** [comment]
You can pass `--no-build windows,lldb` to cut down on some of the time, but we otherwise need to actually build LLVM itself in order to optimize the runtime libraries, which includes asan.

**Comment by pirama-arumuga-nainar** [comment]
Also `--no-lto` will disable LTO when building LLVM, saving some time.

You can also modify the script to do a single-stage build instead of two-stage.  (Feel free to upload a patch to AOSP if you have can enable it using a build option).
