### ISSUE TITLE
[question]Why libclang is missing on Windows?

### ISSUE THREAD

**Issue by perqin** [android/ndk#1491]
On Linux, there is an `libclang.so.11git` (and many other libs) under `toolchains/llvm/prebuilt/linux-x86_64/lib64`. However, most of them are missing on Windows. There is no `libclang.dll` under 'toolchains\llvm\prebuilt\windows-x86_64\lib64`.

Why these libs are missing on Windows? I'm working on a project that relies `libclang` to work properly.

**Comment by DanAlbert** [comment]
We only support building for Android with the NDK, and libclang.dll is something that you'd use to build tools for Windows, so it's outside the scope of what we support. It's only included with the Linux toolchain because we didn't specifically choose to remove it (the NDK toolchain is a copy of the toolchain we use to build the tools used to build AOSP, where host Linux _is_ a target).

Unfortunately if you want to use libclang you'll need to build it yourself because it isn't something we currently have the bandwidth to support.
