### ISSUE TITLE
[BUG] API Level 30 is not supported on NDK r21 LTS

### ISSUE THREAD

**Issue by EwoutH** [android/ndk#1502]
#### Description
Currently the latest LTS build of the Android NDK (r21e) doesn't seem to support the latest stable Android API Level (30).

Over at [google/lyra](https://github.com/google/lyra) we got the [following error](https://github.com/google/lyra/runs/2388488717#step:3:33) when trying to upgrade to the API Level 30:
```
WARNING: API level 30 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 29
```
Targeting the API level 30 is [mandatory](https://support.google.com/googleplay/android-developer/answer/9859152#zippy=%2Ctarget-api-level-requirements-for-the-play-console) for the Google Play store starting from August 2, 2021 for new apps and  from November 1, 2021 for app updates.

#### Environment Details

* NDK Version: r21e, the current LTS release (`21.4.7075529`)
* Build system: [Bazel](https://github.com/bazelbuild/bazel) 4.0.0
* Host OS: Ubuntu 20.04.2 LTS (GitHub [virtual environment](https://github.com/actions/virtual-environments/blob/ubuntu20/20210425.1/images/linux/Ubuntu2004-README.md))
* ABI: arm64-v8a
* NDK API level: 30
* Device API level: 30

**Comment by DanAlbert** [comment]
```
cat android-ndk-r21e/meta/platforms.json 
{
  "min": 16,
  "max": 30,
  "aliases": {
    "20": 19,
    "25": 24,
    "J": 16,
    "J-MR1": 17,
    "J-MR2": 18,
    "K": 19,
    "L": 21,
    "L-MR1": 22,
    "M": 23,
    "N": 24,
    "N-MR1": 24,
    "O": 26,
    "O-MR1": 27,
    "P": 28,
    "Q": 29,
    "R": 30
  }
}
```

Your problem is bazel.

https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/build/lib/bazel/rules/android/ndkcrosstools only includes up to NDK r19. Presumably you're getting downgraded to the r19 crosstool, which stops its support at API 29: https://github.com/bazelbuild/bazel/blob/10fe917f3645a817cf8796e016827e15646ab0bc/src/main/java/com/google/devtools/build/lib/bazel/rules/android/ndkcrosstools/r19/ApiLevelR19.java#L57.
