### ISSUE TITLE
[question] Should the NDK and/or platform provide a shared libatomic?

### ISSUE THREAD

**Issue by smeenai** [android/ndk#1519]
In all versions of the NDK I have on hand (r21 through r23 beta 5), I see a libatomic.a but not a libatomic.so. I'm not sure which libatomic implementation that corresponds to.

compiler-rt's builtins library can provide the libatomic functions, but https://reviews.llvm.org/D47606 disabled that by default. The implementation of those functions relies on maintaining some [internal state](https://github.com/llvm/llvm-project/blob/02c718301b305dff87aa4b204b7b3e6fc647999d/compiler-rt/lib/builtins/atomic.c#L105) in the library, and if you build them into a static library, link different copies of that library into different shared objects, and then try using an address atomically across shared objects, your atomic operations won't be atomic (because of the multiple copies of the state). The only way to make it work is to build a shared libatomic, so that you have a single global copy of the state.

Does the libatomic.a in the NDK have the same issue, and if so, is it worth providing a libatomic.so? I imagine it might not be very common to use an address atomically across shared objects (which would explain why there weren't any LLVM bug reports, as the commit message of https://reviews.llvm.org/D47606 notes), but it's potentially a pretty nasty footgun.

**Comment by DanAlbert** [comment]
We'd discussed the issue and iirc the prevailing opinion was that atomic _types_ would not be a part of an API anyway.

Providing a libatomic.so seems of fairly limited value to me. I don't think it's too much work either, so maybe?

From the platform it'd only be usable by minSdkVersion API 32+, and idk if it's ABI stable or not so any time it changes that minimum resets.

From the NDK it's maybe more useful. None of the tools will know it needs to be packaged in the APK though (not unfixable, just thinking out loud). Most people I talk to don't want to add any more libraries to their APK unless absolutely necessary so wouldn't use it, but I guess if you have an API with this odd requirement you don't have a choice in the matter.

@rprichard

**Comment by rprichard** [comment]
In r22 and older, libatomic.a comes from Android's gcc 4.9. In r23, the atomics are instead part of the builtins archive, but there is an empty libatomic.a for compatibility with -latomic (and maybe there will be a real libatomic.a again in the future?):
```
$ cat /x/android-ndk-r23-beta4/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/12.0.5/lib/linux/aarch64/libatomic.a
/* The __atomic_* APIs are now in libclang_rt.builtins-*.a. They might
   eventually be broken out into a separate library -- see llvm.org/D47606. */
```

AFAIK, on the current Android architectures, libatomic is only used for types larger than 2 machine words, which the language allows but also seems uncommon?

In the platform, maybe we'd export the APIs from libc.so, like we did with the unwinder?

For ABI stability: I think gcc's libatomic exposes both `libat_*` and `__atomic_*` APIs, but compiler-rt only exposes `__atomic_*`. There's another set of APIs that only libgcc has (from http://b/134091978#comment5):
 - `__atomic_{add,and,nand,or,sub,xor}_fetch_{1,2,4,8,16}`: Clang doesn't use them
 - `__atomic_feraiseexcept`: Clang does use it, but maybe GCC does

(If you're following the link internally, that comment also mentions `__atomic_is_lock_free`, but LLVM has since added that API.)

IIRC the two implementations disagree on their level of support for overlapping atomic accesses. gcc tries to support it, and I think compiler-rt doesn't? I *think* gcc's system won't work if some overlapping accesses are small enough to be lock-free, and some aren't. (Aside: that [libat_lock_n](https://github.com/gcc-mirror/gcc/blob/d9f1466f88abef7c814d02ba39a6ea5ef420aaec/libatomic/config/posix/lock.c#L82-L96) function uses an inconsistent lock acquisition order, so it can deadlock once AccessSize * NumThreads is large enough. I should file a bug for this...)

For the NDK, if we use libatomic.so, then NDK users need to redistribute it. I'd guess we don't want that to be the default, because someone using DSOs from different third-parties could then have conflicting copies of libatomic.so. (AFAIK we already have this problem with libc++_shared.so, though?)

I suspect we don't have to worry about shipping a libc++_shared.so linked against libatomic.so, because libc++ probably doesn't access any super-large atomics. (Or, if it did, the accesses to a variable all happen in a single DSO.)

**Comment by rprichard** [comment]
>Aside: that [libat_lock_n](https://github.com/gcc-mirror/gcc/blob/d9f1466f88abef7c814d02ba39a6ea5ef420aaec/libatomic/config/posix/lock.c#L82-L96) function uses an inconsistent lock acquisition order, so it can deadlock once AccessSize * NumThreads is large enough. I should file a bug for this...

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101075

**Comment by smeenai** [comment]
Thanks for all the responses :)

It's fair to say that this is very niche (use of the libatomic functions should be rare to begin with, and using them across `so` boundaries rarer still). It scares me a little to have them included  in compiler-rt (I *think* you had to link against libatomic explicitly, so you could audit for places with potential issues, whereas compiler-rt will just get linked in implicitly), but it'll likely be completely fine in practice.

**Comment by DanAlbert** [comment]
libatomic was automatic for Android for a very long time. It was needed in most cases and libatomic was the answer to a very large proportion of "why is my build broke?" questions.

**Comment by smeenai** [comment]
Sorry, this slipped through the crack on my end! Thanks for all the responses ... I didn't know libatomic used to be automatic, and in that case, I'm pretty sure there's nothing to do here :)
