### ISSUE TITLE
[BUG] Toolchain for Linux do not pass arguments

### ISSUE THREAD

**Issue by nono3551** [android/ndk#1598]
#### Description

I can't build Baresip with NDK r23. Problem seems to be in:
android-ndk-r23\toolchains\llvm\prebuilt\linux-x86_64\bin

Some linked files do not pass given arguments with **"$@"**. This causes errors during compilation. This problem can be found in:
1. clang
2. clang++
3. ld.lld
4. ld64.lld
5. llvm-ranlib
6. ...many more

#### Environment Details

I had this issue when I tried to build Baresip on Windows with WSL (Ubuntu).
NDK: r23
ABI: all

**Comment by DanAlbert** [comment]
`clang` isn't a shell script. It's a symlink.

```
$ file ~/src/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
/home/danalbert/src/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: symbolic link to clang-12
```

If you have text files instead of symlinks, that's the problem, but it's a problem that happened as part of extraction on your machine. The package https://github.com/android/ndk/wiki#current-lts-release contains symlinks. If the `clang` binary didn't work in general none of our tests could have passed.
