### ISSUE TITLE
Visual Studio Android Native unhendle exception

### ISSUE THREAD

**Issue by aharondavid** [android/ndk#1635]
Description
My Native source is under Windows Visual Studio 2022 Anroid Native.
Exceptions doesn't catch despite of compile it with -fexception and -rtti flags.
here are a screen shots of the project definitions:
I will be gratefull for any help.

**Platform Setting:**
![image](https://user-images.githubusercontent.com/41375082/146677416-f1ff3ac1-377d-4a45-9b0a-4bdd5f9572b1.png)

**C++ Setting:**
![image](https://user-images.githubusercontent.com/41375082/146677467-42da7e30-a287-4157-b625-f154ee9ba3a9.png)

**linking Setting:**
![image](https://user-images.githubusercontent.com/41375082/146677486-43581f2f-80e8-4e4a-a4e2-e9426fea7ba6.png)

Here is the output of readelf on my .so
$ readelf.exe -sW libTerraExplorerX.so |grep exception
    41: 00000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_free_exception
    42: 00000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_get_exception_ptr
    56: 00000000     0 FUNC    GLOBAL DEFAULT  UND _ZNSt9exceptionD2Ev
    62: 00000000     0 OBJECT  GLOBAL DEFAULT  UND _ZTISt9exception
    72: 00000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_allocate_exception
    91: 00000000     0 OBJECT  GLOBAL DEFAULT  UND _ZTVSt9exception
    93: 00000000     0 FUNC    GLOBAL DEFAULT  UND _ZSt18uncaught_exceptionv
 61874: 01363049    28 FUNC    WEAK   DEFAULT   11 _ZNSt9exceptionC2ERKS_

**Comment by DanAlbert** [comment]
Maybe https://developer.android.com/ndk/guides/common-problems#rttiexceptions_not_working_across_library_boundaries?

Our tests show that exception handling works so this is probably a build system bug, so this probably needs to be filed with VS rather than with us. https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#Unwinding might help you debug.
