### ISSUE TITLE
[BUG] llvm-readelf -h result is not accurate

### ISSUE THREAD

**Issue by leleliu008** [android/ndk#1643]
![9](https://user-images.githubusercontent.com/3040852/147867040-0261bc76-f426-4b12-bd80-511f403142e3.PNG)

Android NDK:  23.1.7779620

Host Machine: Ubuntu-20.04

**Comment by DanAlbert** [comment]
```
~/src/android-ndk-r24-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-readelf -h ~/src/android-ndk-r24-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang-13
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x56F21C0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          96318664 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         12
  Size of section headers:           64 (bytes)
  Number of section headers:         34
  Section header string table index: 32
```

Provide the input you used please. Will reopen when we get the data we need.

**Comment by leleliu008** [comment]
https://github.com/leleliu008/test/releases/download/20220103-1623/gsed-4.8-bin.tar.xz

**Comment by rprichard** [comment]
Given the underlining, I think the complaint is about `(Shared object file)` versus `(Position-Independent Executable)`?

Both PIE and DSO files have an e_type of ET_DYN, but the parenthesized text, which had been intended to be helpful, is misleading with PIE. It seems that binutils readelf was recently patched to look for DF_1_PIE and change the text to say `Position-Independent Executable` instead.

https://github.com/bminor/binutils-gdb/commit/93df3340fd5ad32f784214fc125de71811da72ff

Most of the complexity is in finding the dynamic table. It looks for PT_DYNAMIC first, and then if it exists, it tries to find a .dynamic section instead, and bails if .dynamic is SHT_NOBITS.

In hindsight, maybe the text should have been `DYN (Dynamically-Linked File)` or something? The e_type in the header doesn't actually distinguish between PIE and DSO files.

"DYN (Shared object file)" [matches](http://www.sco.com/developers/gabi/latest/ch4.eheader.html) the ELF specification, but that's because PIE isn't in the specification. The [dynamic section](http://www.sco.com/developers/gabi/latest/ch5.dynamic.html#dynamic_section) has DT_FLAGS but not DT_FLAGS_1. (DT_FLAGS_1 can have DF_1_PIE.)

**Comment by leleliu008** [comment]
may be this helpful : 
https://github.com/file/file/blame/master/magic/Magdir/elf#L61
https://github.com/file/file/commit/483e7d8f1a5c3544bd42ead471813f8389fa7fc2

**Comment by jfgoog** [comment]
After discussion with teammates, we don't consider this a bug in the NDK.

We agree that the behavior of Gnu readelf is nicer, but we don't expect or need LLVM to behave the same as Gnu in all cases.

If you feel that it's important that this issue be addressed, please re-file with LLVM directly, per https://llvm.org/docs/HowToSubmitABug.html
