### ISSUE TITLE
[question] passing argument to clang

### ISSUE THREAD

**Issue by gladys88-88** [android/ndk#1644]
Hi all,

Understand that the underlying compiler for ndk-build has been switch to clang for c and clang++ for c++. Would like to check how to pass argument to clang using the ndk-build or is it possible to do so in the first place.

I would like to either generate the llvm IR by passing in -emit-llvm -S or pass in my custom llvm pass .so to it. I have tried adding under LOCAL_CFLAGS in the Android.mk but resulted in error building. 

Thanks in advance

**Comment by DanAlbert** [comment]
> I have tried adding under LOCAL_CFLAGS in the Android.mk but resulted in error building.

What error? Because that's how you do it.

**Comment by gladys88-88** [comment]
this is my Android.mk content:

`LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := hello
LOCAL_SRC_FILES := src/hello.c
LOCAL_CFLAGS += -emit-llvm -S
LOCAL_LDLIBS += -fuse-ld=gold
 
include $(BUILD_EXECUTABLE)
`
Error (note: the path below is truncated for displaying here):
/aarch64-linux-android/bin/ld.gold: error: ./obj/local/arm64-v8a/objs/hello/src/hello.o:1:14: invalid character
/aarch64-linux-android/bin/ld.gold: error: ./obj/local/arm64-v8a/objs/hello/src/hello.o:1:14: syntax error, unexpected $end
/aarch64-linux-android/bin/ld.gold: error: ./obj/local/arm64-v8a/objs/hello/src/hello.o: not an object or archive
/sysroot/usr/lib/aarch64-linux-android/24/crtbegin_dynamic.o:crtbegin.c:function _start_main: error: undefined reference to 'main'
/sysroot/usr/lib/aarch64-linux-android/24/crtbegin_dynamic.o:crtbegin.c:function _start_main: error: undefined reference to 'main'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

without the LOCAL_CFLAGS += -emit-llvm -S, i can compile and execute in android phone.

**Comment by stephenhines** [comment]
The problem here is that you're trying to generate an executable from that LLVM IR directly, and the tools won't recognize that. The build rules produce a `.o` or `.s` file that contains the LLVM bitcode instead of binary code or assembly.

Is your custom pass implemented for the Android LLVM version that you're using? LLVM IR isn't portable, so if you're using a version of LLVM that is slightly newer (or older), then you can end up with compatibility problems. Assuming you are using the same version, I think you might be able to load your pass using `-fplugin=YourPass.so` (see https://clang.llvm.org/docs/ClangPlugins.html#using-the-clang-command-line).

**Comment by gladys88-88** [comment]
thanks for the reply, i have try running with the -fplugin and it did load the plugin! However, it complain undefined symbol: _ZNK4llvm10ModulePass17createPrinterPassERNS_11raw_ostreamERKSs' which is what i experiencing when attempting to pass in via clang directly. I have tried setting -D_GLIBCXX_USE_CXX11_ABI=0 when compiling my custom pass as suggested by google search result but still undefined symbol. However, i can load my pass via opt which is why i trying to churn out the llvm IR from ndk-build. 

Is there any way I can generate the IR from ndk-build? If i did not specify the include $(BUILD_EXECUTABLE), ndk-build will complain that there are no modules to build in this project. TIA

**Comment by stephenhines** [comment]
`llvm::ModulePass::createPrinterPass(llvm::raw_ostream&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const` is the function that is trying to find, which basically implies that the plugin you created is incompatible with our version of LLVM (and thus the bitcode might also be incompatible). We don't provide `opt`, so you would be running something that isn't really supported by the NDK. You can try building your pass against the LLVM that we do provide because we do ship the toolchain manifest as part of the NDK prebuilts.

You don't mention which NDK you're using, so I'll assume it is r23, which has `clang-r416183c1`. A copy of that manifest is located [here](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/0625305092d0cfa7e28b0e1b268aff1d3d751eca/clang-r416183c1/manifest_7714059.xml). https://android.googlesource.com/toolchain/llvm_android/+/master#instructions-to-rebuild-a-particular-toolchain-release has instructions for how to rebuild the particular LLVM once you have the manifest file. Again, this isn't something that we officially support, but I can try my best to answer questions if you encounter problems.

**Comment by gladys88-88** [comment]
Thanks for the reply. Appreciate it :)

**Comment by DanAlbert** [comment]
> Is there any way I can generate the IR from ndk-build?

No. Executables, shared libraries, and static libraries are the supported output types.

You're probably best off not trying to use ndk-build for this, but instead following https://developer.android.com/ndk/guides/other_build_systems to call the compiler directly? idk enough about what you're doing to know if that's right or not, but if your goal is not to produce a library or executable then neither ndk-build or CMake is going to be the easy path. In either you could write custom rules, but if that's what you're doing neither of those systems is really helping you.
