### ISSUE TITLE
[BUG] Runtime crash in libc++_shared.so with NDK23(b)

### ISSUE THREAD

**Issue by akaStiX** [android/ndk#1663]
### Description

I got a runtime crash when built our example project with Android NDK 23 and 23b too.
Here's a callstack:
> libart.so!art_sigsegv_fault()
 	libart.so!art::FaultManager::HandleFault(int, siginfo*, void*)()
 	app_process64!art::SignalChain::Handler(int, siginfo*, void*)()
 	[vdso]!()
 	libc++_shared.so!std::__ndk1::codecvt<char, char, mbstate_t>::encoding() const(const std::__ndk1::codecvt<char, char, (anonymous struct)> * this) Line 944
 	libc++_shared.so!std::__ndk1::__stdinbuf<char>::imbue(std::__ndk1::locale const&)(std::__ndk1::__stdinbuf<char> * this, const std::__ndk1::locale & __loc) Line 83
 	libc++_shared.so!std::__ndk1::__stdinbuf<char>::__stdinbuf(__sFILE*, mbstate_t*)(std::__ndk1::__stdinbuf<char> * this, FILE * __fp, std::__ndk1::__stdinbuf<char>::state_type * __st) Line 75
	libc++_shared.so!std::__ndk1::DoIOSInit::DoIOSInit()(std::__ndk1::DoIOSInit * this) Line 110
 	libc++_shared.so!std::__ndk1::ios_base::Init::Init()(std::__ndk1::ios_base::Init * this) Line 151
 	libc++_shared.so!__cxx_global_var_init() Line 79
 	libc++_shared.so!_GLOBAL__sub_I_iostream.cpp()
 	linker64!__dl__ZL10call_arrayIPFviPPcS1_EEvPKcPT_mbS5_()
 	linker64!__dl__ZN6soinfo17call_constructorsEv()
 	linker64!__dl__ZN6soinfo17call_constructorsEv()
 	linker64!__dl__ZN6soinfo17call_constructorsEv()
 	linker64!__dl__Z9do_dlopenPKciPK17android_dlextinfoPKv()
 	linker64!__dl__ZL10dlopen_extPKciPK17android_dlextinfoPKv()
 	libdl.so!android_dlopen_ext()
 
Also this is what I've got in logcat:
>01-30 23:39:57.712 14603 14603 W linker  : Warning: "/data/app/~~1PonpzQ3MONL0eXVLGpXmw==/com.EpicLRT.ActionRPGSample-XzGBy5ciLVwpmuP50lpMnw==/lib/arm64/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
01-30 23:57:09.703 14603 14603 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 14603 (ActionRPGSample), pid 14603 (ActionRPGSample)

This crash doesn't happen when I built my project with NDK 21.
Our main DSO links libc++ statically, however we also use libc++_shared for 3rd party DSOs that we can't change. Perhaps this can cause my crash?

### Affected versions

r23

### Host OS

Windows

### Host OS version

Windows 10

### Affected ABIs

arm64-v8a

### Build system

Other (specify below)

### Other build system

Custom Unreal Engine's build system

### minSdkVersion

21

**Comment by DanAlbert** [comment]
> Our main DSO links libc++ statically, however we also use libc++_shared for 3rd party DSOs that we can't change. Perhaps this can cause my crash?

It's possible. ODR violations can definitely cause crashes. Without a repro case we unfortunately can't help. There's not enough context for us to really even make guesses about what happened here.

Why are you using libc++_static for your app? Does the problem go away if you don't do that?

**Comment by akaStiX** [comment]
>Why are you using libc++_static for your app? 
Unreal Engine overrides new and delete to provide it's own custom allocators. But since libc++ is a library with C++ interface we found a case when new for some internal allocations for std::thread was called in a header and delete for this allocation was called in a corresponding .cpp file. This resulted in new being overridden by our allocator, while delete was executed from within a libc++_shared.so
Since there's no way to inject our own symbols in front of a global symbol look up table on Android (i.e. RTLD_DEEPBIND is not available for dlopen) libc++_shared would pick up a default definition for new\delete.
So we decided to static link it. But some third party libs rely on libc++_shared.so
This worked well with NDK 21.

I can provide a sample and steps to reproduce for this crash, but it will require pulling an entire UE 5.0 and it's sample project to reproduce. This issue didn't happen on another project, so it might be something specific to that sample project. I could, probably, try to pin it down and reduce to a minimal project.
But it would be helpful if you had source code for libc++_shared available, so I could take a look inside myself and see if I can get any clues on what's happening there.

**Comment by DanAlbert** [comment]
> Unreal Engine overrides new and delete to provide it's own custom allocators.

Custom allocators that are not consistent throughout the whole app is another thing that can cause problems. I don't think that's the problem here, but the setup you're describing makes me nervous.

If you're using libc++_shared throughout the app, the first library loaded that defines new/delete (publicly) should be the definition that wins. As long as the UE library with the overrides gets loaded first, it should also affect your other libraries, including libc++. @rprichard to confirm, but I'm fairly confident in that.

> But it would be helpful if you had source code for libc++_shared available, so I could take a look inside myself and see if I can get any clues on what's happening there.

https://cs.android.com/android/platform/superproject/+/master-ndk:toolchain/llvm-project/libcxx/

**Comment by akaStiX** [comment]
>Custom allocators that are not consistent throughout the whole app is another thing that can cause problems.

It is a big problem that we override new\delete mid program execution, but that's how native apps are designed on Android and I have no way to change it.

>I don't think that's the problem here, but the setup you're describing makes me nervous.

Hah, imagine how nervous I am, since I have to fix all those nasty bugs resulting from either solution :D

>If you're using libc++_shared throughout the app, the first library loaded that defines new/delete (publicly) should be the definition that wins. As long as the UE library with the overrides gets loaded first, it should also affect your other libraries, including libc++

We load libUnreal.so as a first thing in our activity. If we link it with libc++_shared, it becomes a dependency and needs to be loaded before UE. As far as I understand a runtime linker here, the definition from UE wouldn't be available for resolution here, libc++_shared would either pick up an existing definition or use it's own (it's a weak symbols).
Even if I am wrong here, it doesn't matter as I examined the list of loaded libs before libUnreal even gets a chance to be loaded and there's plenty of system libs, including libc++, and one of them comes with a definitions for new\delete.
We'd be able to solve this issues if RTLD_DEEPBIN was supported by a runtime linker, but it's not unfortunately.

P.S. Thanks for the link to source code. I'll investigate it more and update this ticket once I'll have more info

**Comment by DanAlbert** [comment]
> It is a big problem that we override new\delete mid program execution, but that's how native apps are designed on Android and I have no way to change it.

Yeah, C++ is actually much more strict than I'm letting on. C++ says this cannot happen, but the authors didn't really have plugin architectures in mind. In practice on android you can mostly think of anything within a single `System.loadLibrary` is its own "program", so as long as the organization here is something like `System.loadLibrary("libapp")` and libapp.so depends on some other things, and all of those depend on libc++_shared.so, the new/delete in libapp.so should be the definitions that get used.

If your dependencies are something like the following, however:

libapp.so -> libunreal.so (libunreal.so has the new/delete replacements) -> libc++_shared.so
libapp.so -> libsomedep.so -> libc++_shared.so

Then I think the definition that gets used depends on the order of the libraries in the `DT_NEEDED` sections in libapp.so. If libunreal.so is first, you get the right definition, otherwise you won't.

> We load libUnreal.so as a first thing in our activity. If we link it with libc++_shared, it becomes a dependency and needs to be loaded before UE.

Ah, are you trying to work around the old jellybean linker bug? I hadn't considered that. Just to be clear: that bug was fixed (in JB MR2, aka API 18, I think). If your minSdkVersion is 19 or higher (NDK r24+ won't support anything lower) you don't need that workaround any more, and should be able to drop the explicit load of libc++_shared.so.

> Even if I am wrong here, it doesn't matter as I examined the list of loaded libs before libUnreal even gets a chance to be loaded and there's plenty of system libs, including libc++, and one of them comes with a definitions for new\delete.

I'm not clear on the linker behavior here. There's been a lot of work related to this that landed in APIs 23 and 24, but I'm not sure about this particular behavior. My expectation based on anecdotes is that the system's own new/delete shouldn't have an impact on the apps (unless you're linking `/system/lib/libstdc++.so` in which case that _is_ the implementation, but that shouldn't be happening if you're using libc++). It wouldn't be too hard to put together a sample app to prove that and I do have some kitkat devices handy, but it's going to be a while before I have a chance to do so.

> P.S. Thanks for the link to source code. I'll investigate it more and update this ticket once I'll have more info

One more thing: it is hard to tell based on the stack trace, but a common ODR violation caused crash is for missed-initialization of globals. I've seen programs end up with two copies of `std::cout`, but only one copy of the static initializer. The initializer runs and initializes one of the globals, but then later the uninitialized global gets used which causes the crash. I don't know if that's the case here, but it wouldn't surprise me.

**Comment by akaStiX** [comment]
Yes, we do an explicit load of libc++_shared.so in our activity before loading libUnreal.so.
Thanks for all the info you provided. I'll revisit this whole thing and after doing some tests will update this ticket.

**Comment by rprichard** [comment]
The linker semantics did change a lot starting in API 23. I'm less familiar with the old semantics -- IIRC it's a bit like https://en.wikipedia.org/wiki/Direct_binding.

IIUC both libunreal.so and libc++_shared.so define new/delete symbols, and we want to consistently use the ones from libunreal.so? In that case, loading libc++_shared.so explicitly, before libunreal.so is loaded, will break things.

When the loader loads a shared object, it resolves the relocations in that object, by searching for symbols. For each relocation, it searches the closure of dependencies, starting with the library passed to loadLibrary/dlopen. It prefers the first symbol definition it finds, in BFS order (breadth-first search).

So, if the first loadLibrary call loads libc++_shared.so, then all the code in libc++_shared.so will prefer to use its own new/delete definitions. Loading another library that needs libc++_shared.so won't alter which definitions were used to relocate libc++_shared.so -- libc++_shared.so will continue to use its own new/delete definitions.

> If your dependencies are something like the following, however:
>
> libapp.so -> libunreal.so (libunreal.so has the new/delete replacements) -> libc++_shared.so
> libapp.so -> libsomedep.so -> libc++_shared.so
>
> Then I think the definition that gets used depends on the order of the libraries in the DT_NEEDED sections in libapp.so. If libunreal.so is first, you get the right definition, otherwise you won't.

If the first dlopen/loadLibrary call loads libapp.so (and therefore libunreal.so, libsomedep.so, libc++_shared.so transitively), then all references to new/delete will use the first new/delete definition found in the list:
 * libapp.so
 * libunreal.so
 * libsomedep.so
 * libc++_shared.so

The order of libunreal.so and libsomedep.so depends on the order of the DT_NEEDED list in libapp.so, but it sounds like only one of them has the definitions, so it doesn't matter?

If there's an extra library, though, then things change:

libapp.so -> libapp2.so -> libunreal.so -> libc++_shared.so
libapp.so -> libsomedep.so -> libc++_shared.so

Now the BFS order from libapp.so might put either of libunreal.so or libc++_shared.so first, depending on the DT_NEEDED order.

> Since there's no way to inject our own symbols in front of a global symbol look up table on Android (i.e. RTLD_DEEPBIND is not available for dlopen) libc++_shared would pick up a default definition for new\delete.

I'm not sure RTLD_DEEPBIND would be helpful -- currently RTLD_GLOBAL libraries mostly aren't added to the global search list, and libc++.so (like other internal libraries) isn't used to lookup app symbols.

If you can have a single loadLibrary call to libapp.so, then all references to new/delete should consistently use the same definitions.

I'm assuming nothing is linked with -Bsymbolic, but if anything else, that would also alter symbol lookup. A library linked with -Bsymbolic prefers its own definitions over those from another shared object. `readelf -d` would show something like:
```
0x000000000000001e (FLAGS)        SYMBOLIC
```
