### ISSUE TITLE
[BUG] _Unwind_Backtrace() or libunwindstack - slow/not working

### ISSUE THREAD

**Issue by Over17** [android/ndk#1666]
### Description

I've almost done with the upgrade from r21d to r23b, having investigated a bunch of perf regressions. Now the "final boss" is stack unwinding which didn't work out of the box.

We have two ways of getting stack trace that are currently in use:
- libunwind _Unwind_Backtrace()
- libunwindstack from AOSP, compiled in as source

The former had caused crashes in signal handlers in the past (I found few bugs which mention NDK r13 and r16b), and we were told by some Google folks that libunwindstack is the way to go and that it should work basically everywhere.

So, we switched to libunwindstack. However, on armv7, its performance was way worse than NDK's libunwind, causing issues for our users who abused logging APIs. :) 

So for armv7, we switched back to _Unwind_Backtrace() (for IL2CPP library only, not for the main engine).

Now I upgraded the NDK and found out stack unwinding is completely broken. So I updated libunwindstack (along with the dependencies) with an Android 12 version from AOSP (tag `android-12.0.0_r27`). Surprisingly, it worked right away for arm64, but is still broken for armv7 for me. (we're using Thumb in case it matters)

Moreover, I ran perf tests which showed on arm64 something like

> 02-02 13:24:38.827 V/Unity   (13264): LibUnwindStack         returned 8 stacktraces in **54076** microseconds
> 02-02 13:24:38.827 V/Unity   (13264): _Unwind_Backtrace returned 8 stacktraces in **28784** microseconds

So, it looks like LibUnwindStack is slower. On Armv7, it's broken, and the performance is like

> 02-01 19:17:41.117 V/Unity   (11796): LibUnwindStack         returned 0 stacktraces in **58514645** microseconds
> 02-01 19:17:41.118 V/Unity   (11796): _Unwind_Backtrace returned 8 stacktraces in **35304** microseconds

:wat: there must be something wrong with libunwindstack - both on perf and functionality side.

So, the question is:
1. what is the preferred/official way of getting stack traces: libunwind (_Unwind_Backtrace()) or libunwindstack?
2. if it's the former, should it work from a signal handler?
3. if it's the latter, why is it so much slower than libunwind? (and why could it be broken on armv7, but I'm diving into our code yet again)

Thanks in advance!

### Affected versions

r23

### Host OS

Windows

### Host OS version

Windows 10

### Affected ABIs

arm64-v8a

### Build system

Other (specify below)

### Other build system

custom

### minSdkVersion

21

### Device API level

31

**Comment by cferris1000** [comment]
I'm not sure I understand your full question. libunwindstack is not a NDK library, so it's not available to regular applications. It's only meant for the platform users.

In addition, it is slower because it does more than the normal unwinder. It was really designed mostly for handling crashes, not as a sampler. However, there is the perfetto system for doing sampling (which does use libunwindstack but it enables a number of options and other methods to make it performant).

To answer your questions:

1. There is no true official way to get stack traces. The only tool available for apps is _Unwind_Backtrace and it's not completely safe (it might crash). It also cannot unwind through any Java frames, only through native stack frames.
2. _Unwind_Backtrace can work through a signal handler but there were some kernels and unwinding information that wasn't correct. It has a tendency to crash when encountering certain kinds of Java frames. The _Unwind_Backtrace code is actually coming from tne NDK itself. A new version of that code was created but I'm not sure what NDK it's available in. But it has the same restrictions of previous versions, it can crash and it only unwinds through native code.
3. I don't know why libunwindstack is broken on armv7, but it's probable that there is some way it's being used which is not supported. I know of no reason that it wouldn't work on armv7. However, it's possible that whatever you are using to generate armv7 does not include unwind information. There are a lot of tests to verify libunwindstack and I haven't noticed any failures on armv7.

So I have some questions:

What are you trying to do? Are you attempting to do some kind of sampling? Do you want to get a stack when crashing?

The only officially supported way of doing sampling is really perfetto. If you want extra information on crashes, there is some methods added in Android 12 (can get access to protobuf of the crash data).

**Comment by Over17** [comment]
Thank you @cferris1000 .

We need the stack traces mostly for exceptions/crashes, but they're also used when logging for example - because the callstack of the logging line is logged ( :) ). It's definitely not for sampling.

As for armv7 not working, looks like `-Wl,--no-rosegment` linker option fixes it; I'm verifying it right now. The solution was inspired by the discussion in #1426 , especially that we are now changing the linker to lld.

> If you want extra information on crashes, there is some methods added in Android 12 (can get access to protobuf of the crash data).

What are the APIs? Happy to look into them.

**Comment by enh-google** [comment]
> We need the stack traces mostly for exceptions/crashes, but they're also used when logging for example - because the callstack of the logging line is logged ( :) ). It's definitely not for sampling.

one thing that's worth considering is multiple unwinders for different jobs... we have three at the moment:

1. the exception handling unwinder. needs to be fast, doesn't need to worry about corrupt state.
2. the MTE unwinder. needs to be *really* fast, doesn't need to worry about corrupt state. (https://android.googlesource.com/platform/bionic/+/master/libc/bionic/android_unsafe_frame_pointer_chase.cpp --- the filename gives away why it's quick, and also its main limitation :-) .)
3. the crash unwinder. needs to give the best diagnostics possible despite likely corruption, but can take an order of magnitude longer than the others.

assuming 32-bit is dead to you (or at least that you can debug on 64-bit), you might find that the frame pointer "unwind" is a better fit for your logging purposes.

> What are the APIs? Happy to look into them.

see https://developer.android.com/reference/android/app/ApplicationExitInfo#getTraceInputStream() --- there's a link to the protobuf schema there too.

**Comment by Over17** [comment]
Thank you @enh-google, this is super helpful and makes total sense. 32-bit is unfortunately more than alive for us 🧟 but having different solutions for different options makes sense.
