### ISSUE TITLE
[BUG] starting r23 `binder_auto_utils.h` does not compile for Android 10.

### ISSUE THREAD

**Issue by atsushieno** [android/ndk#1668]
### Description

I have been using NDK r21 to keep libc++_shared compatibility, and NDK binder for years. These days I'm trying to bump the NDK version to r23, but turned out that it fails to compile NDK binder header `binder_auto_utils.h`

```
In file included from /sources/AAP/android-audio-plugin-framework/native/androidaudioplugin/android/src/gen/org/androidaudioplugin/AudioPluginInterface.cpp:1:
In file included from /home/atsushi/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/binder_parcel_utils.h:29:
/home/atsushi/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/binder_auto_utils.h:263:32: error: 'AStatus_getDescription' is unavailable: introduced in Android 30
```

I reproduced the issue in my public repository: https://github.com/atsushieno/android-audio-plugin-framework/runs/5137116814?check_suite_focus=true

The relevant change was brought in by this commit: https://cs.android.com/android/_/android/platform/frameworks/native/+/e886cfddf915cd82c2767ea11212b2372108ef15

As you can see, it only brings in run-time check and thus it is still part of compiled (not ignored) code in API Level 29, and thus it fails to compile.

It should be reproducible in any code that sets minSdk 29 in build.gradle(.kts) and has a C++ code that has `#include <android/binder_auto_utils.h>`.

### Affected versions

r23, r24, Canary

### Host OS

Linux, Mac, Windows

### Host OS version

Ubuntu 20.04 etc.

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

CMake

### minSdkVersion

29

**Comment by DanAlbert** [comment]
This header was never really supposed to ship in the NDK. I'm supposed to be removing it but haven't found the time. Instead, the header is shipped with the SDK for each API level at `$SDK/platforms/android-32/optional/libbinder_ndk_cpp/android/binder_auto_utils.h` (which is a surprise to me, I was under the impression that this was supposed to be bundled with aidl in build-tools). You'll want to migrate to that, and file the bug... somewhere else. I'm actually not sure where. b.android.com doesn't have anything obvious for aidl or build-tools. @smore-lore, wdyt?

**Comment by atsushieno** [comment]
Also it does not seem to be appropriate to close this issue yet. The problem is present as long as the latest AIDL tool still generates code that references the "wrong" path (from your point of view).

**Comment by DanAlbert** [comment]
Closed doesn't mean we stop responding, it means that there's no work for us to do. The copy of this header that is in the NDK is not supported for the reasons above. We can still help, but whatever we come up with won't be included in an NDK release.

It's not in the API 29 SDK, no. Use a newer one? Your compileSdkVersion need not (and generally should not) match yourinSdkVersion.

**Comment by atsushieno** [comment]
My `compileSdk(Version)` in `build.gradle(.kts)` is already 31. Since AGP passes `minSdk(Version)`to NDK (or CMake), `compileSdk(Version)` is almost irrelevant when it comes to NDK. I thought it is how you folks designed it, but now it smells more like another issue...?

**Comment by DanAlbert** [comment]
Ah, so you have some custom rules in CMake or whatever that you're using to run this? I see.

The SDK version that you use from `$SDK/platforms` should match your `compileSdkVersion`, not your `minSdkVersion`. That property is not passed to ndk-build or CMake because it isn't relevant for any of the cases we actually planned for. You can do that manually with your `cmake.args` or whatever in your build.gradle though.

That header was added to the NDK due to a misunderstanding that it represented platform APIs. In fact, it's tightly coupled to aidl, which is shipped in build-tools. It's being removed from the NDK because the NDK version and build-tools versions are supposed to be uncoupled (it's very common for folks to update their build-tools basically ASAP, but to stay on old NDKs for quite some time). If the header comes from the NDK, each version of build-tools can only be guaranteed to work with one version of the NDK.

Instead the header got moved, but to minimize breakage we left the header in the NDK while people transitioned so that nothing was forced until something broke (like it now has). My understanding was that it was supposed to go into build-tools rather than the SDK (again, they are tightly coupled), but I guess that isn't what happened. I guess the least broken thing to do would be to pass your build-tools version to cmake/ndk-build and use that to find the right header in the SDK?

The fact that the header is in fact wrong for typical app usage is a separate issue, but this isn't the right bug tracker for that (as I said above, I'm not sure where it actually should be filed, but @smore-lore will know).

I know this is basically a workflow made out of sharp edges, but that's because this workflow hasn't actually been implemented yet. For this to work well AGP needs to add support for C++ aidl, but that's an AGP thing, not an NDK thing.

**Comment by atsushieno** [comment]
Ahh, alright, so it is safe to simply pass `-DANDROID_PLATFORM=android-31` in `build.gradle.kts` to cmake. Then it is non-blocking issue for me at all. Thanks for all the hints!

**Comment by DanAlbert** [comment]
No, it definitely isn't if you want you app to run on anything older than 31. Pass a new variable. `-DCOMPILE_SDK_VERSION=31` or whatever.

**Comment by atsushieno** [comment]
I just tried `-DCOMPILE_SDK_VERSION=31' but it did not fix the build. Even with 25.0.8141415.

Reproduced with r23 as:
https://github.com/atsushieno/android-audio-plugin-framework/runs/5172629215?check_suite_focus=true

Does this usage look wrong? https://github.com/atsushieno/android-audio-plugin-framework/blob/8f6abd08ade19e007ff7eb670702dfca918718ae/androidaudioplugin/build.gradle.kts#L27

With `-DANDROID_PLATFORM=31` the errors go away but as per your suggestion it seems no-go for me.

**Comment by atsushieno** [comment]
Filed as https://issuetracker.google.com/issues/219987524.

**Comment by DanAlbert** [comment]
Thanks. I assigned the owner. I also CC'd myself just in case it needs more shepherding.
