### ISSUE TITLE
cannot locate symbol "SL_IID_ANDROIDACOUSTICECHOCANCELLATION"

### ISSUE THREAD

**Issue by aberaud** [android/ndk#1733]
### Description

We get Play Store reports about crashes on a single test device, with our app built with NDK r23 or r25:

`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "SL_IID_ANDROIDACOUSTICECHOCANCELLATION" referenced by "/data/app/.../lib/arm/mylib.so"...`

This happens on the following automatic pre-launch report virtual test device:
Google Pixel 2 (virtual) - Android 9 (SDK 28) - armeabi

Other aarch64 and armv7 devices work fine with the same build.

Can we expect the symbol `SL_IID_ANDROIDACOUSTICECHOCANCELLATION` to be available across all Android devices, and is this just a buggy virtual device image?

If we can't expect this symbol to be available, could this symbol be made a `define` instead, to allow checking for this capability, even on devices without support, as allowed by the OpenSLES API?

### Affected versions

r23, r25

### Host OS

Linux

### Host OS version

Ubuntu 22.04

### Affected ABIs

armeabi-v7a

### Build system

Other (specify below)

### minSdkVersion

21

### Device API level

28

**Comment by aberaud** [comment]
We used `SL_IID_ANDROIDACOUSTICECHOCANCELLATION` with a similar code as this official example:
https://android.googlesource.com/platform/frameworks/wilhelm/+/master/tests/examples/slesTestRecBuffQueue.cpp#387

**Comment by enh-google** [comment]
https://android.googlesource.com/platform/frameworks/wilhelm/+/master/src/libOpenSLES.map.txt#9 says it's been there since API 21, but i note there's no CTS test for it (in fact, that sample code you link is the only file with "test" in the name that references it).

that said, it's surprising that it would be missing on Pixel 2 ... do you see this on any _real_ devices? (i'm wondering whether it's just a mistake in the emulator image? they're often a bit dodgy.)

**Comment by DanAlbert** [comment]
If you can get your hands on a real device, it'd be interesting to compare. It may just be a broken emulator image like @enh-google says. I'd try myself but won't have access to all my devices for a few weeks.

**Comment by rprichard** [comment]
I checked all my virtual emulator images between L and Sv2 and the `/system/{lib,lib64,lib/arm,lib64/arm64}/libOpenSLES.so` files always defined a `SL_IID_ANDROIDACOUSTICECHOCANCELLATION` symbol.

Do you have the fingerprint of the affected virtual device? `adb shell getprop ro.build.fingerprint`

I'm not sure we really have a "Pixel 2" emulator image? It's possible to select a Pixel 2 "device definition" when creating an AVD, but I think that just controls things like screen resolution. e.g. The build fingerprint on a real Pixel 2 device will have something like "walleye" in it, and I can create a Nexus One AVD running an x86_64 P build.

I see the symbol in these emulator images:
 - Android/sdk_phone_x86_64/generic_x86_64:9/PSR1.180720.012/4923214:userdebug/test-keys (x86-64)
 - google/sdk_gphone_x86_arm/generic_x86_arm:9/PSR1.180720.117/5875966:user/release-keys

**Comment by aberaud** [comment]
@rprichard Thanks for the reply.

This problem doesn't happen with Android Studio emulator images but with the Google Play Store pre-launch report virtual test devices. We don't control what devices are used for these automated tests.

**Comment by DanAlbert** [comment]
Hmm. I have no idea what those are running (I had never heard of that until this bug). I'm not really sure where to route you. The only thing I can really say for sure is that it seems like there's no NDK bug here? It sounds like the OS images that are used in that system are non-conforming.

@enh-google, any idea who we should bother, or where that bug should be filed?

(closing because there's nothing to fix in the NDK; we'll still be reading responses here to try to help)

**Comment by enh-google** [comment]
no, https://github.com/flutter/flutter/issues/37396 was a similar issue, and i haven't made any progress finding out who owns these emulators for that. i've added you to that thread and dragged serbanc in to see if he can help...
