### ISSUE TITLE
Clang broken from ndk 23 - not getting arguments

### ISSUE THREAD

**Issue by dec1** [android/ndk#1738]
### Description

calling clang (version **11**) on command line eg to query version works fine with ndk **22**:

`> ndk/22/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi19-clang++ --version`
```
Android (7155654, based on r399163b1) clang version 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315dfbea7c137aa2e6d362dbb457e388158d)
Target: armv7a-unknown-linux-android19
```

Starting with ndk **23** (which ships with clang/llvm version **12**) this breaks. Clang seems not to see any argument passed (here "--version")
```
> ndk/23/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi19-clang++ --version
clang: error: no input files
```
Note that this is reproducible only when the ndk is directly downloaded (eg via webbrowser) from
[here](https://developer.android.com/ndk/downloads), but not when its downloaded by android studio. Its also not reprodubilbe on MasOS

Specifying a file to compile presents the same problem.

Is there something amiss with the ndk 23 (and 25) linux archive at https://developer.android.com/ndk/downloads?

### Affected versions

r23 and r25

### Canary version

none

### Host OS

Linux

### Host OS version

ubuntu 20.10

### Affected ABIs

armeabi-v7a

### Build system

Other (specify below)

### Other build system

calling clang++ directly

### minSdkVersion

none

**Comment by dec1** [comment]
On a mac there seems to be no problem. Maybe this is just and issue with the ndk for linux?

`> /Users/me/Library/Android/sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi19-clang++ --version`


`Android (8481493, based on r416183c2) clang version 12.0.9 (https://android.googlesource.com/toolchain/llvm-project c935d99d7cf2016289302412d708641d52d2f7ee)
Target: armv7a-unknown-linux-android19
Thread model: posix
InstalledDir: /Users/me/Library/Android/sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/darwin-x86_64/bin
`

**Comment by DanAlbert** [comment]
(r23 is no longer supported, so focusing on the r25 aspect here)

I cannot repro this. In a freshly downloaded linux NDK r25:

```bash
$ toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi19-clang++ --version
Android (8490178, based on r450784d) clang version 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6)
Target: armv7a-unknown-linux-android19
Thread model: posix
InstalledDir: /usr/local/google/home/danalbert/src/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin
```

Do you have the same problem if you run the normal `clang++` instead of the triple-prefixed script? The triple-prefixed entry-points are shell scripts:

```bash
#!/bin/bash
bin_dir=`dirname "$0"`
if [ "$1" != "-cc1" ]; then
    "$bin_dir/clang++" --target=armv7a-linux-androideabi19 "$@"
else
    # Target is already an argument.
    "$bin_dir/clang++" "$@"
fi
```

I can't imagine why that wouldn't work on your system aside from your `/bin/bash` not actually being bash.

> Is there something amiss with the ndk 23 (and 25) linux archive at https://developer.android.com/ndk/downloads?

For windows and linux the download URLs on the website are identical to those used by the SDK manager (the same URL, not just copies of identical packages). For Darwin the download URL on the web is a DMG to appease gatekeeper, whereas the SDK downloads a zip file with the layout AGP expects (gatekeeper restrictions do not apply to packages downloaded by the SDK manager).

**Comment by dec1** [comment]
> Do you have the same problem if you run the normal clang++..

Yes.

I download several times (and verified sha1), but with no change in behaviour.

Only the  copy that android studio downloads works.
And the fact that it does seems to indicate that its not an issue with my bash

(I noticed that from r22 -> r23 the some changes in the set of archives available  - this might be just a coincidence, but may be an indication that something in the packaging changed)

**Comment by DanAlbert** [comment]
I'm not sure how to help. This works fine for me, and the exact same download URL is working fine when downloaded by the SDK manager on your machine.

Is your browser quarantining the download or something like that? I'm not aware of any such behavior in debian, but it's impossible to keep up with the entire linux distro ecosystem. Ubuntu and Debian usually agree, and Debian is what I tested with. To my knowledge there isn't even an agreed upon signing mechanism that would make that quarantining viable.

What happens if you download with curl instead of a browser?

> I noticed that from r22 -> r23 the some changes in the set of archives available

For mac only, because Apple requires a DMG for notarized binaries that rely on RPATH.

**Comment by dec1** [comment]
Hello.

The download is fine or the sha1 wouldnt match afterwards, right?

>  entire linux distro ecosystem

This is a recent LTS (k)ubuntu, a very popular distro, hardly something exotic :-)

**Comment by DanAlbert** [comment]
> The download is fine or the sha1 wouldnt match afterwards, right?

Checksum won't cover file metadata. Quarantine flags are often an xattr. That's at least how macOS's quarantines work. As I said, I don't know if such a concept even exists for Linux. I haven't heard of one, I'm just out of ideas and wildly speculating.

**Comment by DanAlbert** [comment]
> I would have thought testing on ubuntu would be valuable anyways.

```bash
$ docker run -itv `realpath src/android-ndk-r25`:/ndk ubuntu
root@44f474404727:/# /ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi19-clang++ --version
Android (8490178, based on r450784d) clang version 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6)
Target: armv7a-unknown-linux-android19
Thread model: posix
InstalledDir: /ndk/toolchains/llvm/prebuilt/linux-x86_64/bin
```


I hate to say it but I really expect this is a problem with your environment. I'd love to help but I don't think I can. Closing because I don't think there's anything to fix in the NDK, but we're still here to answer questions.

**Comment by dec1** [comment]
Hi Dan. 

Just to let you know (and in case else stumbles across the same problem):
It seems the problem I experienced stems from the extraction of the downloaded archive (rather than the downloading itself).
 the problem occurs when I use `Ark` (Gui) to decompress the zip file.
If I extract on the command line instead using `unzip` then the problem does not arise.
Also calculating the extracted dir sha1 using `find ./android-ndk-r25 -type f \( -exec sha1sum "$PWD"/{} \; \) | awk '{print $1}' | sort | sha1sum` yeilded a different sha1 in each case.
Strange that the "incorrect" decompression should "only" manifest itself in clang not seeing the parameters passed. 

Regardless, thanks very much for your patience and help.
