### ISSUE TITLE
[FR] bring back libstdc++

### ISSUE THREAD

**Issue by justusranvier** [android/ndk#1746]
### Description

libc++ [never finished implementing c++17](https://en.cppreference.com/w/cpp/compiler_support/17#C.2B.2B17_library_features) and has only fallen [further](https://en.cppreference.com/w/cpp/compiler_support#C.2B.2B20_library_features) [behind](https://en.cppreference.com/w/cpp/compiler_support#C.2B.2B23_library_features) since then and there is no evidence that the situation is going to improve any time soon.

Now that libc++ is the only standard library available in the NDK this means that c++ projects that want to target Android are increasingly limited to a subset of language features compared to what is available on other platforms.

**Comment by DanAlbert** [comment]
Just to clarify: we're _way_ behind libc++ updates in the NDK, so the NDK is not a good measure of libc++ completeness. That problem is at least nearly solved (see https://github.com/android/ndk/issues/1530).

If there are still missing features in LLVM ToT that are holding you back, could you let us know which? A ton of the things that haven't been implemented in libc++ yet are trivialities, and I assume those aren't what you're referring to. We might be able to get some focus put on whatever is holding you back though.

And don't forget: libstdc++ could not provide complete C++ _11_ on Android.

**Comment by justusranvier** [comment]
Lack of polymorphic allocators in libc++ is the biggest hurdle because it means that on libc++-based platforms I am using std::experimental::pmr::vector and all other platforms I am using std::pmr::vector, which means if I want to use those types in a library api then it requires preprocessor magic to detect the capabilities of the standard library and adjust the api accordingly.

Lack of parallel algorithm support means in cross platform projects we don't even bother using those, because the pain of writing android/apple specific versions of all the functions that might use them is not worth the effort yet.

**Comment by DanAlbert** [comment]
I've forwarded the thread to a coworker that works on libc++. They're OOO though, so will be a while before we hear back.

This FR as titled is not going to be done though. We can't flip back and forth between implementations as one overtakes the other (libc++ was a very clear front runner when we made the switch, even for GNU platforms), nor can we afford to support two. I sympathize that it's frustrating when new features lag behind, but it's not something I have the power to fix (though as I said, I'm going to see if I can get those features some attention). Closing the bug since we won't be pursuing this, but I'll follow up here if I hear anything worth reporting.
