### ISSUE TITLE
[FR] Keep existing support of Objective-C

### ISSUE THREAD

**Issue by Van-der-Deken** [android/ndk#1779]
### Description

This not actually a request to add/implement something, just about intentionally keep functionality already available in NDK.

We've been using shipped LLVM toolchain for compiling Objective-C code since it became default one and everything has been fine, I can't remember anything that could be seen as bug/problem in it (thank you very much for this). Til r23 LTS version this was true, but with r25 LTS we faced the problem, that one of the standard Objective-C sections now missed in the result binary, which prevents us from easy migration to this version and is starting point for this request.

With official answer that NDK doesn't support Objective-C I hope confirming of existing level for any future version won't affect significantly their creation and will not change anything in the answer, except that those who want it will be able to implement it themselves using any version.

**Comment by enh-google** [comment]
i think there's a misunderstanding here --- we didn't _actively_ break objective-c. something changed upstream, and since we don't support objective-c, we also don't test objective-c, so we didn't notice.

we won't suddenly start supporting objective-c, so if you want it to work, you'll have to fix it yourself in llvm. (it'll still be unsupported by us, but since we're not doing anything to _break_ objective-c, if you can keep it working upstream, you'll probably be fine?)

**Comment by Van-der-Deken** [comment]
Thank you for the answer, yes, I'm completely fine with this as understood now why this change happened and be sure in general compatibility of new versions with our needs.
