### ISSUE TITLE
[FR] -fuse-ld=mold -flto support

### ISSUE THREAD

**Issue by truboxl** [android/ndk#1806]
### Description

I am putting this as FR since NDK only supports one linker and unlikely going to reverse course.

Currently mold with `-fuse-ld=mold` can be used on NDK r25 except for arm CMake https://github.com/rui314/mold/issues/864.

But trying to invoke `-fuse-ld=mold -flto` will result in https://github.com/rui314/mold/issues/793.

Mold seems pretty hard on it, thinking it as a `LLVMgold.so` distribution issue.

**Comment by pirama-arumuga-nainar** [comment]
We don't have bandwidth to support `LLVMgold.so` or other linkers in the NDK.  Please follow instructions at https://android.googlesource.com/toolchain/llvm_android/+/refs/heads/master/README.md to build `LLVMgold.so` yourself if you're interested in using `mold`+`lto` on Android.  (https://android-review.git.corp.google.com/c/toolchain/llvm_android/+/1809101 is where we disabled the plugin, and reverting it would be a start).

**Comment by truboxl** [comment]
> https://android-review.git.corp.google.com/c/toolchain/llvm_android/+/1809101

Is there a public accessible version of this website? Or maybe a commit from android.googlesource.com? Thanks

**Comment by stephenhines** [comment]
https://android.googlesource.com/toolchain/llvm_android/+/8543526f90359570f302b0aee3b0fe3b4920ce2b. The other site is where code reviews happen, and should be reachable with an account you create.

**Comment by DanAlbert** [comment]
Since when does gerrit use an internal only URL for googlers even for AOSP? That means we can no longer usefully copy/paste AOSP review URLs :( The URL that was pasted above is android-review.git.corp.google.com, but is identical to https://android-review.googlesource.com/c/toolchain/llvm_android/+/1809101.

I'm going to go file a bug, because that's going to be a passive PITA, but for now if you come across a seemingly invalid link that starts with android-review.git.corp.google.com, just know that you can replace that host with android-review.googlesource.com to get the publicly accessibly URL for the same thing (and we googlers should try to fix the URLs we post publicly).

**Comment by DanAlbert** [comment]
(apparently I'm not the first one to complain, so hopefully that gets fixed soon)
