### ISSUE TITLE
Detecting C compiler ABI info failed to compile with the following output [BUG]

### ISSUE THREAD

**Issue by Desync-o-tron** [android/ndk#1819]
### Description

Hi, first time filing an NDK issue!
I'm trying to follow the CMake support guide (https://developer.android.com/ndk/guides/cmake#command-line_2) but I'm not having much luck.

I have a CMake Project that I want to use. I configured Visual Studio 2022 for the NDK & SDK environment, which is getting seen by CMake. Here's what I'm doing...

```
$ cd ./myproject/build
$ cmake     -DCMAKE_TOOLCHAIN_FILE="C:\Users\lknoble\AppData\Local\Android\Sdk\ndk\25.1.8937393\build\cmake\android.toolchain.cmake"     -DANDROID_ABI=arm64-v8a   -DANDROID_PLATFORM=android-30 ../
```

Here's my [CMakeError.log](https://gist.github.com/Desync-o-tron/d6f5ee0861a2128c46b7f49a49da4d39#file-cmakeerror-log)

### Affected versions

r25

### Host OS

Windows

### Host OS version

Windows 10.0.19044

### Affected ABIs

arm64-v8a

### Build system

CMake

### minSdkVersion

30

**Comment by DanAlbert** [comment]
From the log:

> Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_b5b33.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && MSBuild version 17.4.1+9a89d02ff for .NET Framework

Nothing in the args shown would cause that, so presumably it has to do with the `cmake` that's in your path, or some other environment issue?

We know nothing about the Visual Studio NDK support, so we're not going to be much more help than that. If you're using Visual Studio because you're developing a cross-platform game, see https://developer.android.com/games/agdk. It looks like you're using Microsoft's built-in NDK support though. If you want help with that you'll have to ask Microsoft (my information is way out of date, but the last time I looked the MS support looked like abandonware).

**Comment by Desync-o-tron** [comment]
@DanAlbert thanks for taking the time to respond. After days of looking for documentation that doesn't exist..I agree, vanilla Visual Studio support for the NDK does look like abandonware. I see in the new videos MS are releasing they are recommending users use CMake to support cross platform builds.
