### ISSUE TITLE
[FR] Support Play formatted traces

### ISSUE THREAD

**Issue by garanj** [android/ndk#1898]
### Description

Support traces from Play Console:

in traces from play console addresses look like `0x000000000006263c`
`ndk-stack` expects addresses like `000000000006263c` without leading `0x`

It would be great if `ndk-stack` supported this without the need for additional pre-processing.

**Comment by DanAlbert** [comment]
Can you provide some examples? I have no idea what a play trace looks like. Why is Play mangling the stack trace?

**Comment by samkevich** [comment]
I believe fix should change [this regex](https://android.googlesource.com/platform/ndk/+/refs/heads/master/ndkstack.py#186) to something like `r".* +(#[0-9]+) +pc ([0-9a-fx-x]+) +(([^ ]+).*)"`
It seems `llvm-symbolizer` accepts both address formats: `0x000000000006263c` and `000000000006263c`, so the problem is only in parsing the address

**Comment by DanAlbert** [comment]
@cferris1000, it looks to me like it's not actually anything to do with Play, the trace format just changed at some point? Is that right?

**Comment by DanAlbert** [comment]
@cferris1000 confirmed that the trace format hasn't changed, so it's coming to you mangled from play.

Digging in to fix that though, I think ndk-stack is actually the one doing the mangling, and Play was just kind enough to run ndk-stack (or maybe just addr2line?) for you. But I assume you're running it a second time because you've got more symbol info than Play had? You're probably interested in https://support.google.com/googleplay/android-developer/answer/9848633?#zippy=%2Cnative-generate-a-debug-symbols-file then, and then you won't need `ndk-stack` at all.

That said, I don't think this is hard to fix to allow reprocessing stuff that already went through ndk-stack, so will do that too.

**Comment by DanAlbert** [comment]
Actually that's not what that is. The original crash trace begins with `*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***`, but ndk-stack's output begins with `********** Crash dump: **********`. llvm-addr2line doesn't rewrite that either... I've got no clue what's causing that. Easy fix either way, I just wish I knew why...

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/2915990
