### ISSUE TITLE
[BUG] Build setup issues.

### ISSUE THREAD

**Issue by dexmagic** [android/ndk#1955]
### Description

I created a new NDK project using the wizard/template. I get this error when building

```
C/C++: Platform version '34' is beyond '33', the maximum API level supported by this NDK.
Affected Modules: app
```

When I change the Android API to 33 and build I get this message:

```
1.  Dependency 'androidx.activity:activity:1.8.0' requires libraries and applications that
      depend on it to compile against version 34 or later of the
      Android APIs.

      :app is currently compiled against android-33.

      Also, the maximum recommended compile SDK version for Android Gradle
      plugin 8.0.1 is 33.

      Recommended action: Update this project's version of the Android Gradle
      plugin to one that supports 34, then update this project to use
      compileSdk of at least 34.

      Note that updating a library or application's compileSdk (which
      allows newer APIs to be used) can be done separately from updating
      targetSdk (which opts the app in to new runtime behavior) and
      minSdk (which determines which devices the app can be installed
      on).

```

Here is the build.gradle file the Wizard generated:

```

plugins {
    id 'com.android.application'
}

android {
    namespace 'com.aesirmachina.clangissues'
    compileSdk 33

    defaultConfig {
        applicationId "com.aesirmachina.clangissues"
        minSdk 33
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.10.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}

```

### Affected versions

r26

### Host OS

Mac

### Host OS version

Mac Venture 13.5.2 (22G91)

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

CMake

### minSdkVersion

33

**Comment by dexmagic** [comment]
Here is the version of Android Studio I'm using:

```
Build #AI-222.4459.24.2221.9971841, built on April 19, 2023


Runtime version: 17.0.6+0-17.0.6b802.4-9586694 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

**Comment by DanAlbert** [comment]
This isn't about the NDK, but I think I can help anyway

> Recommended action: Update this project's version of the Android Gradle
> plugin to one that supports 34, then update this project to use
> compileSdk of at least 34.

```gradle
    compileSdk 33
```

You need to change that to 34.

```gradle
        minSdk 33
```

But not this. The error message from CMake tells me that you probably set this to 34 too. If you did not, that's an AGP bug and you need to file it with them (see the "Android Studio and Gradle issues" entry in the NDK's new issue page).

You almost certainly don't want a `minSdkVersion` of 33 either. That means your app will not work on any devices with Android S or older.

When you ran the new project wizard, you were shown this:

![image](https://github.com/android/ndk/assets/315852/82cc7098-1196-4f04-9d3b-f37407bf4aad)

If you clicked "Help me choose", you'd have been shown something like this:

![image](https://github.com/android/ndk/assets/315852/76d1cb48-5ab8-4bd2-8f63-1732a005b444)

Which tells you that your app will only be compatible with 15% of devices.

If you really do want to use `minSdkVersion 34`, you need to upgrade your NDK (you said you're using r26 in the bug report, but your build.gradle says otherwise; r26 is not the default in any version of AGP yet).

**Comment by enh-google** [comment]
are lines like
```
    compileSdk 33
```
initially generated by us? given that compileSdk vs minSdk (and the ndk-build equivalents) do seem to cause a lot of confusion, could we add clarifying comments directly in the generated files?

**Comment by DanAlbert** [comment]
Both are generated by Studio (`compileSdk` I think based on the default for that version of Studio, `minSdkVersion` based on what you choose in the new project wizard), so it depends on what you mean by "us". That FR would need to be filed against Studio.

**Comment by enh-google** [comment]
yeah, that's what i mean --- shouldn't we file a Studio bug and encourage them to make this clearer?

**Comment by DanAlbert** [comment]
If OP wants to do that, b.android.com, file against Studio. The error message was clear to me so I can't explain to them how it's unclear.
