### ISSUE TITLE
Mistyped timestamp parameter in AMediaCodec_queueInputBuffer

### ISSUE THREAD

**Issue by dmikis** [android/ndk#1964]
### Description

The `time` parameter in [misstyped](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/av/media/ndk/include/media/NdkMediaCodec.h;l=295-297;drc=02e84fa4d2059108ccbaf7c028a0114e358f3bab) in the `AMediaCodec_queueInputBuffer` function. It's `uint64_t`, whereas `int64_t` is more appropriate. Negative timestamps are valid (and, e.g. if MP3 or ACC is used for audio, virtually guaranteed). Moreover, it gets immediately implicitly converted back to `int64_t` ([1](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/av/media/ndk/NdkMediaCodec.cpp;l=734;drc=51804e92e8897a81f2cee4c6fe4bda0b20c3949a), [2](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/av/media/libstagefright/MediaCodec.cpp;l=3108;drc=51804e92e8897a81f2cee4c6fe4bda0b20c3949a)). Right now any code that wants to deal with negative timestamp needs to rely on that fact.

### Affected versions

r26

### Host OS

Windows

### Host OS version

10.0.22621 N/A Build 22621

### Affected ABIs

arm64-v8a

### Build system

Other (specify below)

### Other build system

Rust Cargo

### minSdkVersion

32

**Comment by DanAlbert** [comment]
I'm asking around to see if this change is safe or not. The API is nearly a decade old so has already shipped on a few billion devices. The signedness of the type is part of the ABI, but I can't figure out how that ABI break would be symptomatic. I swear I've run into problems over just that kind of mismatch (I want to say it was someone that forced `-fsigned-char` in their app despite Android arm32 systems using unsigned chars), but I don't remember and can't find any record of it.

We have to be pretty cautious. If we decide this is safe, fix it, ship an OS that used that built against that new header, and then later found it wasn't safe, we'd have just broken the API for good.

The alternative is that we add a new API that handles the signed times.

Another wrinkle here is that, yes, you've shown that the current implementation implicitly casts this internally, but we'll have to check that's been true since L, and we're not able to verify that other vendors haven't shipped a different implementation.

**Comment by DanAlbert** [comment]
It sounds like this is probably safe. The compiler doesn't do any conversions between signed and unsigned types, so the OS side won't change, and size promotion happens based on the type of the value, not the type of the destination, so caller code shouldn't change either. It sounds like the case where changing the signedness of an argument can alter behavior is only for types smaller than the register size, and fortunately we're not dealing with any of those here.

I checked the blame and it looks like the implementation hasn't changed since originally written, so that much is safe. As I said before I can't rule out the possibility that another Android vendor has altered the implementation, but it seems unlikely.

The other thing that could possibly be an issue is if this library was ever built with intsan, which would trap on "overflow" in that implicit conversion. We don't currently build that code with intsan, but it's really hard to trace that history. It's uncommon that we removing sanitizers from code though, so unlikely.

If you want this dealt with quickly, refile it against the OS, because it's an OS bug (we're just the delivery mechanism). Use the "Android OS issues" section of https://github.com/android/ndk/issues/new/choose, which will take you to b.android.com, and you want the Media component. If you'd rather one of us do that, we can, but no promises on when we'll have time to do that.

**Comment by dmikis** [comment]
@DanAlbert Thanks for the comprehensive investigation. The problem, indeed, turns out to be a tricky one. Just documenting internal cast as a guaranteed behaviour could be a solution. Ultimately, the mistype doesn't result in incorrect behaviour, just in some developer confusion.

I'll create an OS bug to see what they say about this.

**Comment by DanAlbert** [comment]
> I'll create an OS bug to see what they say about this.

If that gets mistriaged (it happens), let us know and we can unstick it.

**Comment by DanAlbert** [comment]
Closing since there's nothing to do from our end (aside from pulling the latest sysroot once the platform is fixed, but that's part of our regular update process so we don't need to track it).

Did that platform bug get filed? If you link it here I can make sure it hasn't stalled in triage (which does happen).
