### ISSUE TITLE
[BUG]  _LIBCPP_ENABLE_DEBUG_MODE causes linker errors

### ISSUE THREAD

**Issue by AngelDev06** [android/ndk#1972]
### Description

I have a simple cmake project and I am trying to enable iterator debugging. Originally I was doing it with `_LIBCPP_DEBUG` but this no longer works in the latest ndk release as it errors with: `_LIBCPP_DEBUG is not supported anymore. Please use _LIBCPP_ENABLE_DEBUG_MODE instead.` so I went on and used `_LIBCPP_ENABLE_DEBUG_MODE` instead.

However that produces linker errors for some reason and I cannot tell why.
I have the following cache variables in the configure preset:
```
"cacheVariables": {
  "ANDROID_ABI": "armeabi-v7a",
  "ANDROID_ARM_NEON": "TRUE",
  "ANDROID_STL": "c++_shared",
  "CMAKE_CXX_STANDARD": "17"
}
```

### Affected versions

r26

### Host OS

Windows

### Host OS version

Windows 11

### Affected ABIs

armeabi-v7a

### Build system

CMake

### minSdkVersion

21

**Comment by pirama-arumuga-nainar** [comment]
This is expected, because the libc++ in the NDK is not built in Debug mode.  From https://reviews.llvm.org/D122941:

```
This patch shouldn't break any user code, except folks who are building
against a library that doesn't have the debug mode enabled and who try
to enable the debug mode in their code. Such users will get a compile-time
error explaining that this configuration isn't supported anymore.
```

Looking further, the debug mode was also removed [recently](https://discourse.llvm.org/t/rfc-removing-the-legacy-debug-mode-from-libc/71026).  The replacement for it, "hardening" is still going through an [RFC](https://discourse.llvm.org/t/rfc-hardening-in-libc/73925).  [`Safe mode`](https://releases.llvm.org/16.0.0/projects/libcxx/docs/UsingLibcxx.html#enabling-the-safe-libc-mode:~:text=Furthermore%2C%20independently%20of,usually%20be%20respected.)* is probably what can help you in the current release.

\* which will likely get removed when "hardening" is officially supported
