### ISSUE TITLE
clang frontend command failed due to signal[BUG]

### ISSUE THREAD

**Issue by qq545509938** [android/ndk#1991]
### Description

clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
Target: armv7-none-linux-android21
Thread model: posix
InstalledDir: D:\AndroidPlayer\Android-SDK\ndk\20.1.5948944\toolchains\llvm\prebuilt\windows-x86_64\bin
clang++: note: diagnostic msg: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg: 

### Affected versions

Canary

### Canary version

r20b

### Host OS

Windows

### Host OS version

windows 10

### Affected ABIs

armeabi-v7a, arm64-v8a

### Build system

CMake

### minSdkVersion

21

**Comment by DanAlbert** [comment]
> and include the > crash backtrace, preprocessed source, and associated run script.

We can't help without this. The only information in this bug report is "clang crashed", which isn't something we can even begin to investigate.

> r20b

This hasn't been supported for years. Crashes are usually fixed by updating your NDK (r26 is the only supported version). Start there. If that doesn't fix it, attach the repro case Clang asked for (the one generated with r26, the one from r20 is probably not usable) and we'll reopen.
