### ISSUE TITLE
[Bug]: ld.lld: error: undefined symbol: __aeabi_l2d

### ISSUE THREAD

**Issue by jeff2024wang** [android/ndk#1996]
### Description

issue description:
ndk(26) was no longer contain "libgcc.a". So this link error happen...

ld.lld: error: undefined symbol:  __aeabi_d2lz
ld.lld: error: undefined symbol:  __aeabi_l2d

the code:

`double cur_t;`
`long long cur_ns;`
`long a = 0, b = 0;`
`// ... some calculation for a, b ...`

`cur_ns = (long long)a * 1e9 + (long long)b;    // this line is compiled to "__aeabi_d2lz"`
`cur_t = (double)cur_ns / 1e9;   // this line is compiled to  "__aeabi_l2d" `
``// ....``

After libgcc.a is removed from NDK, how to solve this kind of question ?

### Affected versions

r26

### Host OS

Windows

### Host OS version

Windows Server 2012 R2 Standard

### Affected ABIs

armeabi-v7a, arm64-v8a

**Comment by DanAlbert** [comment]
Impossible to say what happened without knowing what you did (code alone is usually useless, we need to know how you compiled it). libgcc is gone because libclang_rt.builtins provides that functionality (as does libunwind, but the symbols you mention come from the builtins). That's in implementation detail that you shouldn't need to concern yourself with though. If you're seeing this probably you're probably erroneously passing `-nostdlib` or similar.

Closing until we get more information, since there's nothing here we can investigate.

**Comment by DanAlbert** [comment]
I don't think that's true? We haven't previously had any reports of pre-libclang code being incompatible with libclang code.

**Comment by jeff2024wang** [comment]
> Impossible to say what happened without knowing what you did (code alone is usually useless, we need to know how you compiled it). libgcc is gone because libclang_rt.builtins provides that functionality (as does libunwind, but the symbols you mention come from the builtins). That's in implementation detail that you shouldn't need to concern yourself with though. If you're seeing this probably you're probably erroneously passing `-nostdlib` or similar.
> 
> Closing until we get more information, since there's nothing here we can investigate.


Sure，there is `LOCAL_LDFLAGS += -nodefaultlibs` in my Android.mk.
After remove it, the issue si solved.
Thank you very much !
