### ISSUE TITLE
[BUG] clang frontend crashes on both r26d and canary version

### ISSUE THREAD

**Issue by yujincheng08** [android/ndk#2012]
### Description

https://godbolt.org/z/3cd8nYMh5

### Upstream bug

llvm/llvm-project#88400

### Commit to cherry-pick

https://github.com/llvm/llvm-project/commit/487967af82053cd08022635a2ff768385d936c80

### Affected versions

r26, Canary

### Canary version

28.0.11699160

### Host OS

Linux, Mac, Windows

### Host OS version

11

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

**Comment by pirama-arumuga-nainar** [comment]
The godbolt repro crashes back to clang 16.  This is not a regression, so we will cherry-pick the fix to r27.

**Comment by DanAlbert** [comment]
Switching godbolt over to the assertions enabled clang shows an assertion failure: https://godbolt.org/z/xh35qaoed

It also fails consistently from clang 16 through HEAD, so not a regression. We might be able to pick up the fix for r27, depending on how invasive it is, but getting the fix into r26e (which isn't currently planned, as there are no regressions against it) seems unlikely.

**Comment by DanAlbert** [comment]
(thank you for the quality bug report, btw, that makes things much easier)

**Comment by yujincheng08** [comment]
upstream fixed: https://github.com/llvm/llvm-project/commit/487967af82053cd08022635a2ff768385d936c80

**Comment by pirama-arumuga-nainar** [comment]
https://r.android.com/3075606 picks the fix into AOSP toolchain.  We'll include the fix in r27.
