### ISSUE TITLE
[DOC] `system_fonts.h`

### ISSUE THREAD

**Issue by th1nk3r-ing** [android/ndk#2034]
### URL

https://developer.android.google.cn/ndk/reference/group/font

### Problem

There is no `ASystemFont_close()` function in the ndk font api.
Should I use the `AFont_close()` ?

**Comment by enh-google** [comment]
yeah, those docs are quite a mess. looks like the docs weren't updated as the API changed during API review. i think https://android-review.googlesource.com/c/platform/frameworks/native/+/3142698 clears everything up.

**Comment by DanAlbert** [comment]
API docs are "automatically" (there's no machine doing it, but it's part of the script I follow) updated as part of the NDK release process when we update the sysroot. Unclear whether there will be a sysroot update between r27 RC 1 and stable or not (we try to avoid making _any_ changes between the final RC and stable), but rest assured that it'll be updated as soon as we're able.

**Comment by DanAlbert** [comment]
I'll leave it open so I remember to consider it before finalizing r27, but I'm unlikely to risk introducing a breaking change in the sysroot for docs only. If we need sysroot updates for other reasons, I'll be sure this gets included, else DAC will have the older docs until r28 beta 1, or maybe an r27 minor release.

**Comment by th1nk3r-ing** [comment]
👌

**Comment by DanAlbert** [comment]
I'm sending r27 final to QA probably this week (I think we've decided to wait for one or two clang fixes, so maybe not), and we don't have other bugs that would require a sysroot update (which the docs are tied to), so we'll pick this up in r28 rather than r27. Not actually much of a delay. It sounds like I'll probably start pushing r28 beta 1 out the door once I'm back from vacation in a couple weeks.

**Comment by DanAlbert** [comment]
Docs won't be live until r28 goes to beta (soonish), but the fix is merged.
