### ISSUE TITLE
can't use ioctl with -Wsign-conversion and non-platform ioctls

### ISSUE THREAD

**Issue by enh** [android/ndk#402]
POSIX says ioctl takes an `int` command, but Linux's _IOC/_IOR/_IOW/_IORW macros generate unsigned constants.

```
#include <drm/drm.h>
#include <fcntl.h>
#include <sys/ioctl.h>

int main(int argc, char** argv) {
  return ioctl(0, DRM_IOCTL_GET_MAGIC, NULL);
}
```

the obvious choices are to either change _IOC to return signed constants or make ioctl take an `unsigned` command.

**Comment by enh** [comment]
https://android-review.googlesource.com/403159

**Comment by colincross** [comment]
Whichever one you change you are changing an API, which may make it harder to port things to bionic.  Maybe just add casts to modules that use -Wsign-conversion?

**Comment by enh** [comment]
the problem is that:

* POSIX says signed.

* glibc says unsigned.

* the Linux kernel internally says unsigned, but...

* the uapi headers are inconsistent. the hard-coded constants are signed, but the _IOC-generated ones are unsigned.

so whatever we do, someone will be unhappy. i wonder if we can use enable_if here to say "ioctl takes an `int` fd, either an `int` or an `unsigned` cmd, then varargs? i'll see what gbiv says...

**Comment by enh** [comment]
https://android-review.googlesource.com/404860 is a (not currently functional) attempt to go the overloading route with clang. (which seems like it might be the only sensible way to do this, if we can get it to work.)

**Comment by gburgessiv** [comment]
Given the comment from srhines at https://android-review.googlesource.com/#/c/406532/, is there a way we could temporarily fix this until an updated libclang finds its way into AOSP?

https://android-review.googlesource.com/404860 relies on enable_if to tiebreak when both overloads are "equally bad" (e.g. when trying to pass an unsigned long into the flags, etc.).

The only other way I can think of to *potentially* fix this in Bionic is macro trickery:

`#define ioctl(...) ioctl(__VA_ARGS__)`

The idea is that clang will see the `__VA_ARGS__` expansion as "in a system header", since the macro was defined in a system header, so it'll silence warnings in `__VA_ARGS__`. I know this because I had to do a bit of cleanup when we swapped snprintf to not be a `#define` in the transition to clang FORTIFY. :) (N.B. As a side-effect, other warnings in arg expansion might be ignored, which could be suboptimal. I haven't actually tested this, though. Happy to do so if it's an approach we want to try.)

Like said, it looks like we can do the overloading thing as soon as we get a new enough libclang+header-abi-dumper (and maybe others that depend on libclang?) into our prebuilts.

**Comment by enh** [comment]
this isn't a regression, it's broken in every other linux libc too (although glibc declares ioctl with an unsigned command, so they'll have trouble with the signed constants instead), and there's an easy workaround, so i'm happy to take as long as we need on this.

**Comment by DanAlbert** [comment]
I'm guessing we have an up to date libclang now. Should this get triaged for r18?

**Comment by stephenhines** [comment]
No, we don't have an updated libclang because these are still using RenderScript's ancient pinned libclang. http://b/64121881 is the blocker here, but we are moving towards getting everything building directly against our prebuilt toolchain libclang instead.

**Comment by DanAlbert** [comment]
Ah, I thought we were getting an updated libclang with each clang update. Gonna throw this in the unplanned bucket then.

**Comment by gburgessiv** [comment]
^ The Bionic change should solve this.

Dunno if the etiquette is to close these when they're fixed in Bionic, or after they're brought into the NDK somehow. So I'm punting this back to you, Dan.

**Comment by DanAlbert** [comment]
Yep, assigning to me to get the NDK updated is the usual process. Thanks for the fix.

**Comment by DanAlbert** [comment]
We've definitely updated the sysroot since then. This was fixed ages ago.
