### ISSUE TITLE
CMAKE_INSTALL_PREFIX in cmake toolchain

### ISSUE THREAD

**Issue by ghost** [android/ndk#458]
#### Description

Im trying to build third-party libraries with the cmake toolchain (`/build/cmake/android.toolchain.cmake`).
This works as expected but the CMAKE_INSTALL_PREFIX isnt set by the toolchain and defaults to `/usr/local`.
I dont tried to install it there, but in cause of the following lines the toolchain shouldnt find it there:
`set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)`
`set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)`
`set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)`

Could the toolchain be changed in a way, that it sets CMAKE_INSTALL_PREFIX to a "right path", where the toolchain can find the installed libraries again?

#### Environment Details

* NDK Version: 15.1.4119039
* Build sytem: cmake
* Host OS: Linux - Fedora 25 (Twenty Five)

**Comment by DanAlbert** [comment]
Sorry, somehow never saw this bug.

I don't really understand what is being asked here. `ONLY` is the correct option for each of these, and `CMAKE_INSTALL_PREFIX` is meaningless with the NDK since you shouldn't be running `make install`.

**Comment by tE3rDA77Sr4WdyTH** [comment]
`ONLY` is the right option here, which is not questioned.

The problem I had was the following:
My application had a dependency to a library.
I usually build a dependency and install it with `make install`, where I just use the default `CMAKE_INSTALL_PREFIX`.
Then in my application I use a FindX.cmake script to find this dependency again.
Since the `CMAKE_INSTALL_PREFIX` isnt set in the NDK, `make install` doesnt work.

After I've seen that you write that one should not use `make install`, I wonder how you deal with dependencies otherwise.

It is also possible, that I generally deal wrong with dependencies in CMake.

**Comment by DanAlbert** [comment]
https://github.com/google/cdep is what we recommend for package management with the NDK, but understandably might be a little heavy-weight for some use cases. Another way to do it would be to link all of your dependencies into the same gradle project, but admittedly I barely know how to use gradle so I can't help you there.

Probably worth thinking about supporting finding compatible NDK libraries that you've installed to your system.

**Comment by DanAlbert** [comment]
I'm grouping this in with the other pending cmake work since whatever I do on this in this release will likely be obsolete when that is done.

**Comment by DanAlbert** [comment]
Now that I've looked at the CMake `find_*` behavior a fair amount, I don't think there's anything for the NDK to do here since there's no sensible default we can set.

But there is a solution to your problem. The docs for the various `find_*` commands show the search behavior. Having tried to do exactly what you described above, the correct way to do this is to set `CMAKE_FIND_ROOT_PATH` to point to the directory where you installed your dependencies. See the doc for the exact directory you should point to, since there are quite a few different options for directory layout for each `find_*` command.
