### ISSUE TITLE
[cmake] toolchain file sets up CMake variables with wrong paths

### ISSUE THREAD

**Issue by akallabeth** [android/ndk#546]
#### Description
* Run CMake build with the NDK toolchain file, dump cmake variables.

The cmake toolchain file does set up the library and include paths in an invalid fashion.
Here a sample dump:

```
CMAKE_SYSROOT=/home/nin/projects/android/android-sdk-linux/ndk-bundle/sysroot
CMAKE_SYSTEM_INCLUDE_PATH=
CMAKE_SYSTEM_LIBRARY_PATH=/home/nin/projects/android/android-sdk-linux/ndk-bundle/platforms/android-21/arch-x86/usr/lib;/usr/lib/w32api;/usr/X11R6/lib;/usr/lib/X11;/usr/pkg/lib;/opt/csw/lib;/opt/lib;/usr/openwin/lib
CMAKE_FIND_ROOT_PATH=/home/nin/projects/android/android-sdk-linux/ndk-bundle
CMAKE_PREFIX_PATH=
CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
CMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY
```

The `CMAKE_SYSTEM_LIBRARY_PATH` contains the path to the android NDK libraries, but due to `CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY` it is never found. According to https://cmake.org/cmake/help/v3.0/command/find_file.html the suitable location would be `CMAKE_FIND_ROOT_PATH`
`CMAKE_FIND_ROOT_PATH` on the other hand holds the path to the NDK but should actually provide the location of header and library locations

#### Environment Details
NDK 16.0.4293906 rc1

**Comment by alexcohn** [comment]
No, none of these libraries that are installed **on** and **_for_** your Linux machine should be visible for Android toolchain:

- /usr/lib/w32api
- /usr/X11R6/lib
- /usr/lib/X11
- /usr/pkg/lib
- /opt/csw/lib
- /opt/lib
- /usr/openwin/lib

**Comment by akallabeth** [comment]
@alexcohn Well, as far as I understand the CMake documentation, the variables with ```_SYSTEM_``` contain the paths on the host, whereas the ```CMAKE_FIND_ROOT_PATH``` is used (as base path) to search for the cross compiler toolchain paths. (and for manually adding paths, the ```CMAKE_INCLUDE_PATH``` and ```CMAKE_LIBRARY_PATH```).

btw, these strange paths you listed are not from my machine environment, they are somehow inserted by the toolchain file...

**Comment by DanAlbert** [comment]
We have tests that show that `find_library` works. What's the bug you're seeing?

**Comment by akallabeth** [comment]
@DanAlbert Due to ```CMAKE_FIND_ROOT_PATH``` being the android NDK base directory it is not detecting the libraries and includes correctly. I don't know what your tests cover, but I get inconsistent linkage and include paths per arch. (specifically x86_64, which is also my host), where host include files are detected somehow.

What I'd like to be able to do is give an additional ```CMAKE_FIND_ROOT_PATH``` to my custom libs and have them detected like on every other platform, but that is currently not working (at least not consistently for all android architectures)

**Comment by alexcohn** [comment]
If you want to manipulate `CMAKE_FIND_ROOT_PATH`, there is nothing that can stop you. You can define additional paths on command line, e.g.

        externalNativeBuild {
            cmake {
                arguments "-DCMAKE_FIND_ROOT_PATH=/abc"
            }
        }

Or you can extend it in your **CMakeLists.txt**, e.g.

    list(APPEND CMAKE_FIND_ROOT_PATH "/def")

As easy as that.

**Comment by akallabeth** [comment]
@alexcohn Yes, but the missing cross toolchain library and include paths are then reason for breakage. Of course I could just add the NDK paths manually, but they should be already set up by the toolchain file.

**Comment by alexcohn** [comment]
not at all, `/home/nin/projects/android/android-sdk-linux/ndk-bundle` is not replaced, but appended. The first approach adds path(s) in front, the second - to the end of the **CMAKE_FIND_ROOT_PATH** list.

**Comment by akallabeth** [comment]
@alexcohn Where do you read about stuff being replaced? The thing I'm complaining about are the **MISSING** paths for **CMAKE_FIND_ROOT_PATH** and the **INCORRECT** addition of the toolchain library path to **CMAKE_SYSTEM_LIBRARY_PATH** (which is **NOT** used when cross compiling)

**Comment by alexcohn** [comment]
Which paths are missing in **CMAKE_FIND_ROOT_PATH**? By default, it looks at **${ANDROID_NDK}** and will find all libraries defined by NDK. As I showed above, you can easily add custom roots if you need them.

Regarding **CMAKE_SYSTEM_LIBRARY_PATH**, you should read [the whole story](https://android.googlesource.com/platform/ndk/+/master/build/cmake/android.toolchain.cmake#332). The first entry in this list is set for current target platform, while the other directories (/usr/lib/w32api; /usr/X11R6/lib; /usr/lib/X11; /usr/pkg/lib; /opt/csw/lib; /opt/lib; /usr/openwin/lib`) are built-in by **cmake** upstream. On my Mac they are set even though none of them exists. So, at least for me, they can make no harm.

**Comment by DanAlbert** [comment]
Here's what we test for `find_library`: https://android.googlesource.com/platform/ndk/+/master/tests/build/cmake-find_library/ That's just the core NDK testing for it. The samples exercise it a bit more.

Can you provide a test case showing the problem? You've told us the paths are "wrong", but I'm not sure what you think "right" is, so I have no way of fixing this.

> Well, as far as I understand the CMake documentation, the variables with _SYSTEM_ contain the paths on the host, whereas the CMAKE_FIND_ROOT_PATH is used (as base path) to search for the cross compiler toolchain paths. (and for manually adding paths, the CMAKE_INCLUDE_PATH and CMAKE_LIBRARY_PATH).

It's possible that CMake isn't considering android x86 to be a cross compile, since it's the same architecture. That assumption is entirely wrong, but I've seen various autoconf builds make the same assumption.

**Comment by alexcohn** [comment]
> CMake isn't considering android x86 to be a cross compile

No, for ARM build, it puts my ARM libs on the first place of the CMAKE_SYSTEM_LIBRARY_PATH list.

> the paths are "wrong", but I'm not sure what you think "right" is

Yes, the other paths in this list: /usr/lib/w32api; /usr/X11R6/lib; /usr/lib/X11; /usr/pkg/lib; /opt/csw/lib; /opt/lib; /usr/openwin/lib are definitely wrong. I get them on my Mac, where none of these exists.

**Comment by akallabeth** [comment]
@DanAlbert CMake considers (as far as I have observed) everything as cross compile as long as ```CMAKE_FIND_ROOT_PATH_MODE_*``` variables are set to ```ONLY``` which the toolchain file does.
Adding anything to ```CMAKE_SYSTEM_*``` variables at this point is useless, as those variables are excluded by CMake from include/library searches.

**Comment by DanAlbert** [comment]
Going to be giving a whole bunch of attention to cmake in r19 or r20 which should cover this.

**Comment by astraujums** [comment]
If you want to use find_library to find your own libraries from a path you specify, use `NO_CMAKE_FIND_ROOT_PATH` option in find_library (e.g. `find_library(MY_LIB my PATHS ${MY_LIB_DIR} NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)`). The NDK toolchain changes the CMAKE_FIND_ROOT_PATH and it gets appended to whatever path you specify but `NO_CMAKE_FIND_ROOT_PATH` option disables this behavior.

**Comment by DanAlbert** [comment]
Here's what each of the variables in question look for a hello world with a modern NDK:

```
CMAKE_SYSROOT=/usr/local/google/home/danalbert/src/ndk/out/linux/android-ndk-r21-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot
```

This one is correct.

```
CMAKE_SYSTEM_INCLUDE_PATH=/usr/include/w32api;/usr/X11R6/include;/usr/include/X11;/usr/pkg/include;/opt/csw/include;/opt/include;/usr/openwin/include
CMAKE_SYSTEM_LIBRARY_PATH=/usr/lib/arm-linux-androideabi/16;/usr/lib/w32api;/usr/X11R6/lib;/usr/lib/X11;/usr/pkg/lib;/opt/csw/lib;/opt/lib;/usr/openwin/lib
```

This has a lot of stuff in it that shouldn't be, but this is actually the same behavior as upstream. [Android.cmake] includes [Linux.cmake] which includes [UnixPaths.cmake] which always adds these paths. The only thing we could do would be to clobber each of them so that they contain only what we set, but that would also clobber anything the user sets via the command line, so we can't do that. This needs to be fixed upstream, not in the NDK.

[Android.cmake]: https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/Platform/Android.cmake#L1
[Linux.cmake]: https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/Platform/Linux.cmake#L52
[UnixPaths.cmake]: https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/Platform/UnixPaths.cmake#L44

```
CMAKE_FIND_ROOT_PATH=/usr/local/google/home/danalbert/src/ndk/out/linux/android-ndk-r21-canary
```

CMake behavior requires that it be set to *something* or all of the `ONLY` behaviors have no effect and CMake will wrongly match system headers and libraries on a Linux system. The current value is the most appropriate path to be used as a base for the various `find_*` commands that CMake has, and this path is automatically prepended to each path searched by those.

https://cmake.org/cmake/help/latest/command/find_path.html#command:find_path

> The CMake variable CMAKE_FIND_ROOT_PATH specifies one or more directories to be prepended to all other search directories. This effectively “re-roots” the entire search under given locations.

Note that this variable is a list. Setting this does not preclude the user from setting their own search paths.

```
CMAKE_PREFIX_PATH=
```

https://cmake.org/pipermail/cmake-developers/2012-January/014583.html explains this one well, and this one we actually did have wrong. https://android-review.googlesource.com/c/platform/ndk/+/1122014 fixes this.
