### ISSUE TITLE
NDK 18 hide symbols

### ISSUE THREAD

**Issue by huangqinjin** [android/ndk#829]
I create a simple project with android studio 3.2.1 (with latest ndk) including c++ support. Add the following code to `native-lib.cpp`:
```c
#define HIDDEN __attribute__((visibility("hidden")))
HIDDEN int FLAGS_hello = 1;
HIDDEN int FLAGS_world = 2;
extern "C" JNIEXPORT int helloworld() { return FLAGS_hello + FLAGS_world; }
```
Run `readelf -s libnative-lib.so | grep FLAGS` for all ABIs and Debug/Release variants, I got the following output:

Debug:
```
armeabi-v7a:
  8482: 00019004     4 OBJECT  LOCAL  HIDDEN    20 FLAGS_hello
  8483: 00019008     4 OBJECT  LOCAL  HIDDEN    20 FLAGS_world

arm64-v8a:
  1634: 0000000000044008     4 OBJECT  LOCAL  DEFAULT   20 FLAGS_hello
  1666: 000000000004400c     4 OBJECT  LOCAL  DEFAULT   20 FLAGS_world

x86:
  6697: 00032004     4 OBJECT  LOCAL  HIDDEN    22 FLAGS_hello
  6698: 00032008     4 OBJECT  LOCAL  HIDDEN    22 FLAGS_world

x86_64:
   551: 0000000000036008     4 OBJECT  LOCAL  HIDDEN    22 FLAGS_hello
   552: 000000000003600c     4 OBJECT  LOCAL  HIDDEN    22 FLAGS_world
```

Release:
```
armeabi-v7a:
     4: 00019004     4 OBJECT  GLOBAL DEFAULT   20 FLAGS_hello
     5: 00019008     4 OBJECT  GLOBAL DEFAULT   20 FLAGS_world
  8549: 00019004     4 OBJECT  GLOBAL DEFAULT   20 FLAGS_hello
  8550: 00019008     4 OBJECT  GLOBAL DEFAULT   20 FLAGS_world

arm64-v8a:
  1549: 0000000000041008     4 OBJECT  LOCAL  DEFAULT   20 FLAGS_hello
  1579: 000000000004100c     4 OBJECT  LOCAL  DEFAULT   20 FLAGS_world

x86:
  5601: 0002f004     4 OBJECT  LOCAL  HIDDEN    22 FLAGS_hello
  5602: 0002f008     4 OBJECT  LOCAL  HIDDEN    22 FLAGS_world

x86_64:
   544: 0000000000033008     4 OBJECT  LOCAL  HIDDEN    22 FLAGS_hello
   545: 000000000003300c     4 OBJECT  LOCAL  HIDDEN    22 FLAGS_world
```

Symbols were not hidden in `Release + armeabi-v7a`. But if I replace `helloworld()` with
```
extern "C" JNIEXPORT int helloworld() { return FLAGS_hello; }
```
then same output got as Debug mode. I'm also confused with the Visibility of `arm64-v8a` being `DEFAULT` rather than `HIDDEN`.

**Comment by rprichard** [comment]
arm64 is special because it defaults to the gold linker, while the other three targets default to bfd. On all four targets, the linker is correctly leaving the symbol out of `.dynsym` for debug builds, but gold marks the local symbol visibility as local, while bfd uses hidden. I would guess that either visibility is fine, but I haven't researched it.

With the arm32 release build, on the other hand, the symbol is output as global in both `.symtab` and `.dynsym`. That looks like a Clang bug with the GlobalMerge pass, which is enabled with -Oz or -O3. It appears that it's dropping the visibility information.

```c++
int somevar1 __attribute__((visibility("hidden"))) = 1;
int somevar2 __attribute__((visibility("hidden"))) = 2;
int get() {
  return somevar1 + somevar2;
}
```

```
clang -target arm -Oz test.cpp -c && readelf -s test.o | grep somevar
     7: 00000000     4 OBJECT  GLOBAL DEFAULT    6 somevar1
     8: 00000004     4 OBJECT  GLOBAL DEFAULT    6 somevar2
```

Turning off the pass works around the issue (as would -Os or -O2):
```
clang -target arm -Oz test.cpp -c -mllvm -enable-global-merge=0 && readelf -s test.o | grep somevar
    10: 00000000     4 OBJECT  GLOBAL HIDDEN     6 somevar1
    11: 00000004     4 OBJECT  GLOBAL HIDDEN     6 somevar2
```

(All of my symbols are marked GLOBAL rather than LOCAL because I'm dumping symbols from an object file rather than a shared object.)

**Comment by srvasn** [comment]
Thanks @rprichard, your answer worked for me on NDK r20b.

**Comment by DanAlbert** [comment]
clang-r383902 in our prebuilts doesn't have this problem any more, not a regression from r20, and has a workaround. Triaging to r22.
