### ISSUE TITLE
[BUG] Incompatible new and delete operators

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#934]
In our infrastructure we have overloaded definitions of new & delete to detect memory leaks. When new is called, we are allocating memory and storing the allocated address in custom map. Similarly when delete is called, we are clearing the instance from map and deallocating memory. We crash the program if same address that is present in map is tried to be pushed into map again.

All our code is present in one shared library, let me call it "LibXYZ" for convenience.

This infrastructure is working fine with GNUSTL. But the same infrastructure is crashing when we use Libc++. We analyzed and found it to be because of std::thread.

This is what happening.

1. In LibXYZ, there is a call to std::thread(). Thread constructor is part of thread header file, and thread header file is included in shared library(i.e in cpp of file shared library). So when std::thread() is called, overloaded "new" in LibXYZ is getting called and allocation is pushed into map.

```
template <class _Fp, class ..._Args,
          class
         >
thread::thread(_Fp&& __f, _Args&&... __args)
{
     //some code
    _TSPtr __tsp(new __thread_struct);
    //some more code
}
```

2. Once thread completes its execution, thread destructor will be called. Thread destructor is present in thread.cpp which is part of libc++_shared.so. As libc++_shared.so uses its internal delete, So any deallocation done during the thread destruction will not be tracked . This way, allocations done in step 1 are ignored to be removed from map.

3. There are few more allocations called in our code. Some times same addresses returned in step 1 are returned because they are freed in step 2. To track the allocation we will try to push this address into map, and program crashes.

Since new & delete operators can be overloaded, allowing the allocations through header files and deallocating them in libc++_shared.so will always result erroneous results .

I think, allocation and deallocation should be taken care by same owner(atleast in the case of Libc++ library). That is, if libc++ is allocating memory, it should take responsibility of deallocating memory. Similarly, if allocating memory is given to other libraries through header files, then deallocation responsibility should also be given to other libraries.
 
Dear Team, could you please share your thoughts?

**Comment by DanAlbert** [comment]
(I'm assuming we're talking about an app here, where you're loading into a Java process with `dlopen`/`System.loadLibrary`. If that's not the case here than this advice isn't really relevant and I'll need to know more about what you're doing.)

Replacement new/delete really can't work as specified when the replacements are loaded after the program has started. How should the following code behave?

```c++
int* x = new int{0};
dlopen("libwithreplacementallocators.so", RTLD_GLOBAL | RTLD_NOW);
delete x;
```

According to the spec, a replacement definition *anywhere in the program* replaces the default definition, so the `delete` should be using a different allocator than the `new` it was allocated with. However, that behavior would be quite broken.

If you're looking for a workaround, you could possibly try checking that your library's replacements have the correct visibility. I think in theory as long as they have public visibility they will be used by libc++ since libc++ is loaded indirectly via the `dlopen` of LibXYZ. Check `readelf -sW LibXYZ | grep -P '_Z(n|d)'`. libc++ has symbols like this:

<details>

```bash
$ readelf -sW sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++_shared.so | grep -P '_Z(n|d)'  
   593: 0005f219    68 FUNC    WEAK   DEFAULT   13 _Znwj
   599: 0005f347     4 FUNC    WEAK   DEFAULT   13 _ZnajSt11align_val_t
   646: 0005f369     4 FUNC    WEAK   DEFAULT   13 _ZdlPvSt11align_val_tRKSt9nothrow_t
   656: 0005f36d     6 FUNC    WEAK   DEFAULT   13 _ZdlPvjSt11align_val_t
   875: 0005f37b     6 FUNC    WEAK   DEFAULT   13 _ZdaPvjSt11align_val_t
   920: 0005f34b    26 FUNC    WEAK   DEFAULT   13 _ZnajSt11align_val_tRKSt9nothrow_t
   938: 0005f2a5     4 FUNC    WEAK   DEFAULT   13 _ZdaPvRKSt9nothrow_t
   941: 0005f25d    26 FUNC    WEAK   DEFAULT   13 _ZnwjRKSt9nothrow_t
   988: 0005f29d     4 FUNC    WEAK   DEFAULT   13 _ZdlPvj
  1094: 0005f377     4 FUNC    WEAK   DEFAULT   13 _ZdaPvSt11align_val_tRKSt9nothrow_t
  1266: 0005f2ad   128 FUNC    WEAK   DEFAULT   13 _ZnwjSt11align_val_t
  1520: 0005f295     4 FUNC    WEAK   DEFAULT   13 _ZdlPv
  1559: 0005f365     4 FUNC    WEAK   DEFAULT   13 _ZdlPvSt11align_val_t
  1813: 0005f299     4 FUNC    WEAK   DEFAULT   13 _ZdlPvRKSt9nothrow_t
  1915: 0005f2a1     4 FUNC    WEAK   DEFAULT   13 _ZdaPv
  2017: 0005f2a9     4 FUNC    WEAK   DEFAULT   13 _ZdaPvj
  2076: 0005f373     4 FUNC    WEAK   DEFAULT   13 _ZdaPvSt11align_val_t
  2080: 0005f32d    26 FUNC    WEAK   DEFAULT   13 _ZnwjSt11align_val_tRKSt9nothrow_t
  2119: 0005f277     4 FUNC    WEAK   DEFAULT   13 _Znaj
  2240: 0005f27b    26 FUNC    WEAK   DEFAULT   13 _ZnajRKSt9nothrow_t
 36348: 0005f295     4 FUNC    WEAK   DEFAULT   13 _ZdlPv
 36383: 0005f219    68 FUNC    WEAK   DEFAULT   13 _Znwj
 37941: 0005f2a1     4 FUNC    WEAK   DEFAULT   13 _ZdaPv
 38004: 0005f2a5     4 FUNC    WEAK   DEFAULT   13 _ZdaPvRKSt9nothrow_t
 38005: 0005f373     4 FUNC    WEAK   DEFAULT   13 _ZdaPvSt11align_val_t
 38006: 0005f377     4 FUNC    WEAK   DEFAULT   13 _ZdaPvSt11align_val_tRKSt9nothrow_t
 38007: 0005f2a9     4 FUNC    WEAK   DEFAULT   13 _ZdaPvj
 38008: 0005f37b     6 FUNC    WEAK   DEFAULT   13 _ZdaPvjSt11align_val_t
 38009: 0005f299     4 FUNC    WEAK   DEFAULT   13 _ZdlPvRKSt9nothrow_t
 38010: 0005f365     4 FUNC    WEAK   DEFAULT   13 _ZdlPvSt11align_val_t
 38011: 0005f369     4 FUNC    WEAK   DEFAULT   13 _ZdlPvSt11align_val_tRKSt9nothrow_t
 38012: 0005f29d     4 FUNC    WEAK   DEFAULT   13 _ZdlPvj
 38013: 0005f36d     6 FUNC    WEAK   DEFAULT   13 _ZdlPvjSt11align_val_t
 38014: 0005f277     4 FUNC    WEAK   DEFAULT   13 _Znaj
 38015: 0005f27b    26 FUNC    WEAK   DEFAULT   13 _ZnajRKSt9nothrow_t
 38016: 0005f347     4 FUNC    WEAK   DEFAULT   13 _ZnajSt11align_val_t
 38017: 0005f34b    26 FUNC    WEAK   DEFAULT   13 _ZnajSt11align_val_tRKSt9nothrow_t
 38018: 0005f25d    26 FUNC    WEAK   DEFAULT   13 _ZnwjRKSt9nothrow_t
 38019: 0005f2ad   128 FUNC    WEAK   DEFAULT   13 _ZnwjSt11align_val_t
 38020: 0005f32d    26 FUNC    WEAK   DEFAULT   13 _ZnwjSt11align_val_tRKSt9nothrow_t
```

</details>

In your library you should see `GLOBAL DEFAULT` instead of `WEAK DEFAULT`.

Like I said though, I don't think replacement new/delete are really advisable for a plugin architecture (and that's what JNI is), so you should probably consider other options for leak detection. Without knowing more about what you're trying to do I can't suggest much other than trying [ASan](https://github.com/google/sanitizers/wiki/AddressSanitizerOnAndroid).
