### ISSUE TITLE
[BUG]Clang doesn't handle __attribute__((aligned)) correctly in arm

### ISSUE THREAD

**Issue by qtiuto** [android/ndk#937]
This bug existed in all clang version that I can test.
Complie the existed example in clang and gcc for arm
```cpp
#include <stddef.h>

struct A{
    char a;
    char b __attribute__((aligned));
};

static_assert(offsetof(struct A,b)==8,"gg");
```
Clang will generate a compile error unless you change 8 to 16.
According to aapcs, max alignment for arm is 8 and  __attribute__((aligned)) should be seen as 8 byte alignment rather than 16 though it's a common case for other cpus. 

This bug has been talked in http://clang-developers.42468.n3.nabble.com/attribute-aligned-always-aligns-to-16-bytes-td4057857.html. 
Can you report it to clang?

**Comment by enh** [comment]
my understanding is that the clang folks think this is working as intended. from https://android.googlesource.com/platform/ndk/+/master/docs/ClangMigration.md#how-to-fix-common-problems:

Normally the `__aligned__` attribute is given an explicit alignment, but with no value means “maximum alignment”. The interpretation of “maximum” differs between GCC and Clang: Clang includes vector types too so for ARM GCC thinks the maximum alignment is 8 (for `uint64_t`), but Clang thinks it’s 16 (because there are NEON instructions that require 16-byte alignment). Normally this shouldn’t matter because malloc is always at least 16-byte aligned, and `mmap` regions are page (4096-byte) aligned. Most code should either specify an explicit alignment or use `alignas` instead.
