### ISSUE TITLE
[BUG] argument unused during compilation: '-Wa,--noexecstack' if -flto=thin is enabled

### ISSUE THREAD

**Issue by wang-bin** [android/ndk#942]
#### Description

add_compile_options(-flto=thin)

#### Environment Details

* NDK Version: 19.0.5232133
* Build system: CMake
* Host OS: Mac
* ABI: armeabi-v7a, arm64-v8a
* NDK API level: 16

**Comment by DanAlbert** [comment]
I think this is already fixed in r20 since the execstack flag is now passed by the driver, but I need to check that we actually have a change that new and that CMake no longer passes it.

**Comment by DanAlbert** [comment]
Never mind, the change is still waiting for review: https://reviews.llvm.org/D53343

**Comment by wang-bin** [comment]
The patch is wrong. clang warns only if compiles with lto, and for any target, not only android. For example you can test on linux x64 host

    clang-9 -Wa,--noexecstack -c a.c  # no warning
    clang-9 -flto -Wa,--noexecstack -c a.c # warning

I guess that's because lto compiles source into bitcode, but not assembly, so assembler flag `--noexecstack` is not used.

**Comment by DanAlbert** [comment]
It won't make that command line not emit a warning, no, but that's because it's not supposed to. Clang is correct to emit that warning.

What the patch does is pass that flag by default where appropriately so that it doesn't need to be passed by ndk-build/CMake, which means you won't get the warning because the flag won't be used except when necessary.

**Comment by wang-bin** [comment]
Sounds right, my mistake.

**Comment by DanAlbert** [comment]
Was in r21.
